import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
import{getActiveVehicle,getVehicles,saveVehicles,syncCommonUi,readJson,writeJson,addNotification}from'../core/app-state.js';
initSidebar();syncCommonUi();
const RFID_KEY='voltdrive_rfid_cards';
const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let cards=readJson(RFID_KEY,[{id:'rfid-primary',name:'VoltDrive key card',number:'•••• 1037',vehicleId:getActiveVehicle().id,status:'active',isDefault:true}]);
function toast(message){const node=$('#access-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(window.accessToast);window.accessToast=setTimeout(()=>node.classList.remove('is-visible'),2300)}
function modal(id,open){const node=$(id);node.classList.toggle('is-open',open);node.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''}
function renderSummary(){const vehicle=getActiveVehicle();$('#access-summary').innerHTML=`<article><span>Active vehicle</span><strong>${escapeHtml(vehicle.manufacturer)} ${escapeHtml(vehicle.model)}</strong></article><article><span>RFID cards</span><strong>${cards.filter(card=>card.status==='active').length} active</strong></article><article><span>Plug & Charge</span><strong>${vehicle.plugAndCharge?'Enabled':'Not enabled'}</strong></article><article><span>Default method</span><strong>${vehicle.plugAndCharge?'Plug & Charge':'Mobile app'}</strong></article>`}
function renderCards(){const vehicles=getVehicles();const list=$('#rfid-list');if(!cards.length){list.innerHTML='<div class="rfid-empty">No RFID cards added yet.</div>';return}list.innerHTML=cards.map(card=>{const vehicle=vehicles.find(item=>item.id===card.vehicleId)||vehicles[0];return`<article class="rfid-item${card.status==='blocked'?' is-blocked':''}" data-id="${card.id}"><span class="rfid-item__icon">▣</span><div><strong>${escapeHtml(card.name)} ${card.isDefault?'<small>· Default</small>':''}</strong><small>${escapeHtml(card.number)} · ${escapeHtml(vehicle.manufacturer)} ${escapeHtml(vehicle.model)} · ${card.status}</small></div><div class="rfid-item__actions">${!card.isDefault&&card.status==='active'?'<button type="button" data-action="default" title="Set default">✓</button>':''}<button type="button" data-action="block" title="Block or unblock">${card.status==='blocked'?'↻':'⊘'}</button><button type="button" data-action="remove" title="Remove">×</button></div></article>`}).join('')}
function renderPnc(){const vehicle=getActiveVehicle();$('#pnc-panel').innerHTML=`<div class="pnc-status"><div><strong>${escapeHtml(vehicle.manufacturer)} ${escapeHtml(vehicle.model)}</strong><small>${vehicle.plugAndCharge?'Certificate active and ready':'Enable automatic vehicle identification'}</small></div><label class="switch"><input id="pnc-toggle" type="checkbox" ${vehicle.plugAndCharge?'checked':''}><span></span></label></div><div class="pnc-certificate"><div><span>Certificate ID</span><strong>${vehicle.plugAndCharge?'PC-AM-84A7-29':'Not issued'}</strong></div><div><span>Status</span><strong>${vehicle.plugAndCharge?'Valid until Aug 2028':'Disabled'}</strong></div></div>${vehicle.plugAndCharge?'<button class="button button--secondary" id="renew-certificate" type="button">Renew certificate</button>':''}`;$('#pnc-toggle').addEventListener('change',event=>{const vehicles=getVehicles().map(item=>item.id===vehicle.id?{...item,plugAndCharge:event.target.checked}:item);saveVehicles(vehicles,vehicle.id);renderAll();toast(event.target.checked?'Plug & Charge enabled.':'Plug & Charge disabled.')});$('#renew-certificate')?.addEventListener('click',()=>toast('Certificate renewed for this prototype.'))}
function renderVehicleOptions(){const vehicles=getVehicles();$('#rfid-vehicle').innerHTML=vehicles.map(v=>`<option value="${v.id}">${escapeHtml(v.manufacturer)} ${escapeHtml(v.model)}</option>`).join('')}
function renderAll(){syncCommonUi();renderSummary();renderCards();renderPnc();renderVehicleOptions()}
$('#scan-qr-button').addEventListener('click',()=>modal('#qr-modal',true));document.querySelectorAll('[data-close-qr]').forEach(node=>node.addEventListener('click',()=>modal('#qr-modal',false)));
$('#simulate-scan-button').addEventListener('click',()=>{modal('#qr-modal',false);sessionStorage.setItem('voltdrive_charger_code','AM-YM-101');toast('Charger AM-YM-101 identified.');setTimeout(()=>location.href='./charging.html?source=qr&charger=AM-YM-101',600)});
$('#use-code-button').addEventListener('click',()=>{const code=$('#charger-code').value.trim();if(!code){toast('Enter a charger code.');return}sessionStorage.setItem('voltdrive_charger_code',code);location.href=`./charging.html?source=code&charger=${encodeURIComponent(code)}`});
$('#add-rfid-button').addEventListener('click',()=>modal('#rfid-modal',true));document.querySelectorAll('[data-close-rfid]').forEach(node=>node.addEventListener('click',()=>modal('#rfid-modal',false)));
$('#rfid-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);cards=[{id:`rfid-${Date.now()}`,name:String(data.get('name')).trim(),number:String(data.get('number')).trim(),vehicleId:String(data.get('vehicle')),status:'active',isDefault:cards.length===0},...cards];writeJson(RFID_KEY,cards);addNotification({category:'charging',title:'RFID card added',message:'A new RFID card can now authorize charging sessions.',priority:'normal'});modal('#rfid-modal',false);renderAll();toast('RFID card added.')});
$('#rfid-list').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const id=button.closest('[data-id]')?.dataset.id;const card=cards.find(item=>item.id===id);if(!card)return;if(button.dataset.action==='default')cards=cards.map(item=>({...item,isDefault:item.id===id}));if(button.dataset.action==='block')cards=cards.map(item=>item.id===id?{...item,status:item.status==='blocked'?'active':'blocked',isDefault:item.status==='blocked'?item.isDefault:false}:item);if(button.dataset.action==='remove')cards=cards.filter(item=>item.id!==id);if(cards.length&&!cards.some(item=>item.isDefault&&item.status==='active')){const first=cards.find(item=>item.status==='active');if(first)first.isDefault=true}writeJson(RFID_KEY,cards);renderAll();toast(button.dataset.action==='remove'?'RFID card removed.':'RFID settings updated.')});
$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});window.addEventListener('voltdrive:state',renderAll);renderAll();
