import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',currency:'AMD',vehicle:{manufacturer:'Tesla',model:'Model Y'}};
const vehicleName=`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`;
const fallbackSessions=[
{id:'CS-0001542',type:'session',location:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue',date:'2026-08-03T10:57:00',status:'completed',energy:31.8,duration:2520,cost:4216,charger:'Charger 101',connector:'CCS2',startBattery:34,endBattery:78,paymentStatus:'paid'},
{id:'CS-0001488',type:'session',location:'Republic Square Charge Hub',address:'1 Republic Square',date:'2026-07-29T19:14:00',status:'completed',energy:22.4,duration:1860,cost:3024,charger:'Charger 204',connector:'CCS2',startBattery:45,endBattery:74,paymentStatus:'paid'},
{id:'CS-0001409',type:'session',location:'Northern Avenue Chargers',address:'10 Northern Avenue',date:'2026-07-21T08:42:00',status:'failed',energy:0.4,duration:240,cost:0,charger:'Charger 301',connector:'CCS2',startBattery:28,endBattery:28,paymentStatus:'cancelled'}
];
const fallbackReservations=[
{id:'RSV-824531',type:'reservation',location:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue',date:'2026-08-06T18:30:00',status:'confirmed',reservationType:'Any available charger',target:80,duration:60,fee:500,accessCode:'482915'},
{id:'RSV-771204',type:'reservation',location:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway',date:'2026-07-26T14:00:00',status:'completed',reservationType:'Specific parking bay',target:85,duration:90,fee:500,accessCode:'105722'}
];
const fallbackPayments=[
{id:'PAY-009812',type:'payment',location:'Yerevan Mall EV Station',date:'2026-08-03T10:58:00',status:'completed',amount:4216,method:'Visa •••• 4242',description:'Charging session CS-0001542',tax:703},
{id:'PAY-009301',type:'payment',location:'Republic Square Charge Hub',date:'2026-07-29T19:15:00',status:'completed',amount:3024,method:'Wallet balance',description:'Charging session CS-0001488',tax:504},
{id:'PAY-008955',type:'payment',location:'Wallet top-up',date:'2026-07-20T12:20:00',status:'completed',amount:10000,method:'Visa •••• 4242',description:'Balance top-up',tax:0}
];
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
const last=readJson('voltdrive_last_session');
if(last&&last.status==='completed')fallbackSessions.unshift({id:`CS-${String(Date.now()).slice(-7)}`,type:'session',location:last.location,address:'Yerevan, Armenia',date:last.completedAt,status:'completed',energy:last.energy,duration:last.duration,cost:last.cost,charger:last.charger,connector:last.connector,startBattery:42,endBattery:last.battery,paymentStatus:'paid'});
const activeReservation=readJson('voltdrive_active_reservation');
if(activeReservation)fallbackReservations.unshift({id:activeReservation.number,type:'reservation',location:activeReservation.location,address:activeReservation.address,date:`${activeReservation.date}T${activeReservation.time}:00`,status:activeReservation.status,reservationType:activeReservation.type,target:Number(activeReservation.target),duration:Number(activeReservation.duration),fee:500,accessCode:activeReservation.accessCode});
const data={sessions:fallbackSessions,reservations:fallbackReservations,payments:fallbackPayments};
let activeTab='sessions';let selected=null;
const currency=user.currency||'AMD';
const fmtMoney=v=>`${Number(v||0).toLocaleString()} ${currency}`;
const fmtDate=v=>new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'});
const fmtDuration=v=>`${Math.max(1,Math.round(Number(v||0)/60))} min`;
const statusClass=s=>s==='completed'?'success':s==='confirmed'||s==='active'?'info':s==='failed'||s==='cancelled'?'error':'warning';
const statusLabel=s=>s.charAt(0).toUpperCase()+s.slice(1);
function syncUser(){const initials=(user.name||'VD').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase();$('#sidebar-name').textContent=user.name||'VoltDrive Driver';$('#sidebar-email').textContent=user.email||'driver@voltdrive.am';$('#avatar').textContent=initials;$('#vehicle-selector').textContent=vehicleName}
function iconFor(type,status){if(type==='session')return status==='failed'?'!':'ϟ';if(type==='reservation')return'▣';return'▤'}
function rowTemplate(item){const primary=item.type==='payment'?item.description:item.location;const secondary=item.type==='payment'?item.location:fmtDate(item.date);let c1='',c2='',c3='';if(item.type==='session'){c1=`<div class="activity-cell"><strong>${item.energy.toFixed(1)} kWh</strong><span>Energy</span></div>`;c2=`<div class="activity-cell"><strong>${fmtDuration(item.duration)}</strong><span>Duration</span></div>`;c3=`<div class="activity-cell"><strong>${fmtMoney(item.cost)}</strong><span>Cost</span></div>`}else if(item.type==='reservation'){c1=`<div class="activity-cell"><strong>${fmtDate(item.date)}</strong><span>Arrival</span></div>`;c2=`<div class="activity-cell"><strong>${item.target}%</strong><span>Target</span></div>`;c3=`<div class="activity-cell"><strong>${fmtMoney(item.fee)}</strong><span>Fee</span></div>`}else{c1=`<div class="activity-cell"><strong>${fmtMoney(item.amount)}</strong><span>Amount</span></div>`;c2=`<div class="activity-cell"><strong>${item.method}</strong><span>Method</span></div>`;c3=`<div class="activity-cell"><strong>${item.tax?fmtMoney(item.tax):'—'}</strong><span>Tax</span></div>`}return `<button class="activity-row" type="button" data-id="${item.id}"><div class="activity-primary"><span class="activity-icon activity-icon--${statusClass(item.status)}">${iconFor(item.type,item.status)}</span><span><strong>${primary}</strong><span>${secondary}</span></span></div>${c1}${c2}<span class="status-badge status-badge--${statusClass(item.status)} activity-status">${statusLabel(item.status)}</span><span class="activity-action">→</span></button>`}
function render(){const query=$('#activity-search').value.trim().toLowerCase(),status=$('#status-filter').value;const items=data[activeTab].filter(i=>(status==='all'||i.status===status)&&JSON.stringify(i).toLowerCase().includes(query));const headings=activeTab==='sessions'?['Session','Energy','Duration','Status','']:activeTab==='reservations'?['Reservation','Arrival','Target','Status','']:['Payment','Amount','Method','Status',''];$('#activity-content').innerHTML=items.length?`<div class="activity-list-header">${headings.map(h=>`<span>${h}</span>`).join('')}</div>${items.map(rowTemplate).join('')}`:'';$('#activity-empty').hidden=items.length>0;$$('.activity-row').forEach(n=>n.addEventListener('click',()=>openDrawer(data[activeTab].find(i=>i.id===n.dataset.id))))}
function detailRows(rows){return `<div class="detail-section"><h3>Details</h3>${rows.map(([a,b])=>`<div class="detail-row"><span>${a}</span><strong>${b}</strong></div>`).join('')}</div>`}
function openDrawer(item){selected=item;$('#drawer-eyebrow').textContent=item.type==='session'?'Charging session':item.type==='reservation'?'Reservation':'Payment';$('#drawer-title').textContent=item.id;let hero='',rows=[],footer='';if(item.type==='session'){hero=`<div class="detail-hero"><span class="status-badge status-badge--${statusClass(item.status)} detail-hero__status">${statusLabel(item.status)}</span><strong>${item.energy.toFixed(1)} kWh</strong><span>${item.location} · ${fmtDate(item.date)}</span></div>`;rows=[['Vehicle',vehicleName],['Location',item.location],['Charger',item.charger],['Connector',item.connector],['Battery',`${item.startBattery}% → ${item.endBattery}%`],['Duration',fmtDuration(item.duration)],['Total',fmtMoney(item.cost)],['Payment',statusLabel(item.paymentStatus)]];footer=`<button class="button button--secondary" id="report-button" type="button">Report issue</button><button class="button button--primary" id="receipt-button" type="button">Download receipt</button>`}else if(item.type==='reservation'){hero=`<div class="detail-hero"><span class="status-badge status-badge--${statusClass(item.status)} detail-hero__status">${statusLabel(item.status)}</span><strong>${item.location}</strong><span>${fmtDate(item.date)}</span></div>`;rows=[['Vehicle',vehicleName],['Type',item.reservationType],['Address',item.address],['Target battery',`${item.target}%`],['Duration',`${item.duration} minutes`],['Reservation fee',fmtMoney(item.fee)],['Access code',item.accessCode]];footer=`<button class="button button--secondary" id="modify-button" type="button">Modify</button><button class="button button--primary" id="navigate-button" type="button">Navigate</button>`}else{hero=`<div class="detail-hero"><span class="status-badge status-badge--${statusClass(item.status)} detail-hero__status">${statusLabel(item.status)}</span><strong>${fmtMoney(item.amount)}</strong><span>${item.description}</span></div>`;rows=[['Date',fmtDate(item.date)],['Merchant',item.location],['Payment method',item.method],['Tax',item.tax?fmtMoney(item.tax):'Not applicable'],['Transaction ID',item.id],['Status',statusLabel(item.status)]];footer=`<button class="button button--secondary" id="dispute-button" type="button">Report a problem</button><button class="button button--primary" id="invoice-button" type="button">Download invoice</button>`}$('#drawer-body').innerHTML=hero+detailRows(rows);$('#drawer-footer').innerHTML=footer;$('#activity-drawer').classList.add('is-open');$('#activity-drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';bindDrawerActions()}
function closeDrawer(){$('#activity-drawer').classList.remove('is-open');$('#activity-drawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function toast(message){const n=$('#activity-toast');n.textContent=message;n.classList.add('is-visible');clearTimeout(window.activityToast);window.activityToast=setTimeout(()=>n.classList.remove('is-visible'),2400)}
function bindDrawerActions(){$('#receipt-button')?.addEventListener('click',()=>{location.href=`./receipt.html?id=${encodeURIComponent(selected?.id||'')}`});$('#invoice-button')?.addEventListener('click',()=>{location.href=`./receipt.html?id=${encodeURIComponent(selected?.id||'')}`});[['#report-button','Support request opened.'],['#modify-button','Reservation editor will open from Reservations.'],['#navigate-button',`Navigation started to ${selected?.location||'location'}.`],['#dispute-button','Payment issue form opened.']].forEach(([s,m])=>$(s)?.addEventListener('click',()=>toast(m)))}
$$('.activity-tab').forEach(n=>n.addEventListener('click',()=>{$$('.activity-tab').forEach(x=>x.classList.remove('is-active'));n.classList.add('is-active');activeTab=n.dataset.tab;$('#status-filter').value='all';render()}));$('#activity-search').addEventListener('input',render);$('#status-filter').addEventListener('change',render);$('#drawer-close').addEventListener('click',closeDrawer);$('#drawer-backdrop').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});$('#logout-button').addEventListener('click',()=>{clearSession();location.href='./login.html'});$$('[data-coming-soon]').forEach(n=>n.addEventListener('click',e=>{e.preventDefault();toast(`${n.dataset.comingSoon} will be added in a later stage.`)}));
syncUser();render();
