import{requireSession}from'../core/route-guard.js';if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';import{initSidebar}from'../layout/sidebar.js';import{syncCommonUi,getSessions,getUser,readJson,writeJson}from'../core/app-state.js';
initSidebar();syncCommonUi();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const user=getUser();const currency=user.currency||'AMD';
const fallback=[
{id:'CS-0001542',location:'Yerevan Mall EV Station',completedAt:'2026-08-03T10:57:00',status:'completed',energy:31.8,duration:2520,cost:4216,connector:'CCS2',reservationFee:500,parkingFee:0,idleFee:0},
{id:'CS-0001488',location:'Republic Square Charge Hub',completedAt:'2026-07-29T19:14:00',status:'completed',energy:22.4,duration:1860,cost:3024,connector:'CCS2',reservationFee:0,parkingFee:0,idleFee:0},
{id:'CS-0001440',location:'Dalma Garden Station',completedAt:'2026-07-17T14:20:00',status:'completed',energy:28.7,duration:2280,cost:3588,connector:'CCS2',reservationFee:500,parkingFee:300,idleFee:0},
{id:'CS-0001390',location:'Yerevan Mall EV Station',completedAt:'2026-07-08T09:10:00',status:'completed',energy:35.7,duration:2760,cost:5042,connector:'CCS2',reservationFee:0,parkingFee:0,idleFee:420},
{id:'CS-0001315',location:'Cascade Parking Charge',completedAt:'2026-06-22T20:15:00',status:'completed',energy:18.6,duration:5100,cost:2046,connector:'Type 2',reservationFee:0,parkingFee:400,idleFee:0},
{id:'CS-0001409',location:'Northern Avenue Chargers',completedAt:'2026-07-21T08:42:00',status:'interrupted',energy:.4,duration:240,cost:0,connector:'CCS2'}
];
const saved=getSessions().map(s=>({...s,completedAt:s.completedAt||s.date||new Date().toISOString()}));const sessions=[...saved,...fallback.filter(f=>!saved.some(s=>s.id===f.id))];let period='month';
const fmtMoney=v=>`${Math.round(Number(v||0)).toLocaleString()} ${currency}`;const completed=s=>s.status==='completed';
function periodSessions(){const count=period==='month'?4:period==='quarter'?6:12;return sessions.slice(0,count)}
function toast(message){const n=$('#analytics-toast');n.textContent=message;n.classList.add('is-visible');clearTimeout(window.analyticsToast);window.analyticsToast=setTimeout(()=>n.classList.remove('is-visible'),2300)}
function chartValues(list){const buckets=period==='month'?['Week 1','Week 2','Week 3','Week 4']:period==='quarter'?['Jun','Jul','Aug','Sep','Oct','Nov']:['Jan','Mar','May','Jul','Sep','Nov'];const vals=Array(buckets.length).fill(0);list.filter(completed).forEach((s,i)=>vals[i%vals.length]+=Number(s.energy||0));if(!vals.some(Boolean))return buckets.map((_,i)=>8+i*3);return vals.map(v=>Number(v.toFixed(1)))}
function render(){const list=periodSessions();const good=list.filter(completed);const energy=good.reduce((n,s)=>n+Number(s.energy||0),0);const cost=good.reduce((n,s)=>n+Number(s.cost||0)+Number(s.reservationFee||0)+Number(s.parkingFee||0)+Number(s.idleFee||0),0);const all=list.length;const duration=good.reduce((n,s)=>n+Number(s.duration||0),0);$('#metric-energy').textContent=`${energy.toFixed(1)} kWh`;$('#metric-cost').textContent=fmtMoney(cost);$('#metric-average').textContent=`${energy?Math.round(cost/energy):0} ${currency}/kWh`;$('#metric-sessions').textContent=String(good.length);$('#success-rate').textContent=`${all?Math.round(good.length/all*100):0}% completion rate`;$('#energy-change').textContent=period==='month'?'+12% vs previous month':'Selected demo period';$('#cost-change').textContent=period==='month'?'+6% vs previous month':'Includes all fees';
 const labels=period==='month'?['Week 1','Week 2','Week 3','Week 4']:period==='quarter'?['Jun','Jul','Aug','Sep','Oct','Nov']:['Jan','Mar','May','Jul','Sep','Nov'];const values=chartValues(list),max=Math.max(...values,1);$('#energy-chart').innerHTML=values.map((v,i)=>`<div class="bar-column"><strong>${v.toFixed(1)}</strong><i style="height:${Math.max(6,v/max*175)}px"></i><span>${labels[i]}</span></div>`).join('');$('#chart-total').textContent=`${energy.toFixed(1)} kWh total`;
 const energyCost=good.reduce((n,s)=>n+Number(s.cost||0),0),reservation=good.reduce((n,s)=>n+Number(s.reservationFee||0),0),parking=good.reduce((n,s)=>n+Number(s.parkingFee||0),0),idle=good.reduce((n,s)=>n+Number(s.idleFee||0),0);const parts=[['Energy',energyCost,'#e82127'],['Reservation',reservation,'#3b82f6'],['Parking',parking,'#f59e0b'],['Idle fee',idle,'#32d583']];$('#ring-total').textContent=Math.round(cost).toLocaleString();$('#breakdown-list').innerHTML=parts.map(([name,value,color])=>`<div class="breakdown-item" style="--dot:${color}"><i></i><span>${name}</span><strong>${fmtMoney(value)}</strong></div>`).join('');
 $('#habit-duration').textContent=`${good.length?Math.round(duration/good.length/60):0} min`;$('#habit-energy').textContent=`${good.length?(energy/good.length).toFixed(1):0} kWh`;const connectors={};good.forEach(s=>connectors[s.connector||'CCS2']=(connectors[s.connector||'CCS2']||0)+1);$('#habit-connector').textContent=Object.entries(connectors).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';const hours=good.map(s=>new Date(s.completedAt).getHours());const avgHour=hours.length?Math.round(hours.reduce((a,b)=>a+b,0)/hours.length):0;$('#habit-time').textContent=avgHour<12?'Morning':avgHour<18?'Afternoon':'Evening';
 const places={};good.forEach(s=>places[s.location||'Unknown station']=(places[s.location||'Unknown station']||0)+1);const ranked=Object.entries(places).sort((a,b)=>b[1]-a[1]).slice(0,3);$('#station-ranking').innerHTML=ranked.map(([name,count],i)=>`<div class="station-rank"><span>${i+1}</span><div><strong>${name}</strong><small>${count} completed session${count===1?'':'s'}</small></div><strong>${Math.round(count/Math.max(good.length,1)*100)}%</strong></div>`).join('')||'<p>No completed sessions in this period.</p>';
 const co2=energy*.39,fuel=energy*.082,trees=co2/1.8;$('#co2-saved').textContent=`${co2.toFixed(1)} kg CO₂ saved`;$('#trees-equivalent').textContent=trees.toFixed(1);$('#fuel-avoided').textContent=`${fuel.toFixed(1)} L`;$('#impact-copy').textContent=`Estimated from ${energy.toFixed(1)} kWh delivered in the selected period.`;renderBudget(cost)}
function renderBudget(cost){const limit=Number(localStorage.getItem('voltdrive_charging_budget')||20000);const pct=Math.min(100,cost/limit*100);$('#budget-used').textContent=fmtMoney(cost);$('#budget-limit').textContent=fmtMoney(limit);$('#budget-progress').style.width=`${pct}%`;$('#budget-message').textContent=cost>limit?`Budget exceeded by ${fmtMoney(cost-limit)}.`:`${fmtMoney(Math.max(0,limit-cost))} remaining in this period.`;$('#budget-input').value=limit}
$$('[data-period]').forEach(b=>b.onclick=()=>{$$('[data-period]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');period=b.dataset.period;render()});
$('#export-analytics').onclick=()=>{const payload={exportedAt:new Date().toISOString(),period,sessions:periodSessions()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`voltdrive-analytics-${period}.json`;a.click();URL.revokeObjectURL(a.href);toast('Analytics data exported')};
const modal=$('#budget-modal');$('#edit-budget').onclick=()=>{modal.classList.add('is-open');modal.setAttribute('aria-hidden','false')};$$('[data-close-budget]').forEach(b=>b.onclick=()=>{modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true')});$('#save-budget').onclick=()=>{const value=Math.max(1000,Number($('#budget-input').value||20000));localStorage.setItem('voltdrive_charging_budget',String(value));modal.classList.remove('is-open');render();toast('Monthly charging budget updated')};$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});render();
