import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
import{getUser,getActiveVehicle,getWallet,getActiveReservation,getSessions,unreadNotifications,syncCommonUi}from'../core/app-state.js';
initSidebar();syncCommonUi();
const user=getUser(),vehicle=getActiveVehicle(),wallet=getWallet(),reservation=getActiveReservation(),sessions=getSessions().filter(s=>s.status==='completed').slice(0,2);
const set=(s,v)=>{const n=document.querySelector(s);if(n)n.textContent=v};
set('#welcome-name',(user.name||'Driver').trim().split(/\s+/)[0]);set('#vehicle-name',`${vehicle.manufacturer||'Tesla'} ${vehicle.model||'Model Y'}`);set('#vehicle-registration',vehicle.registration||'35 EV 777');set('#connector',vehicle.connector||'CCS2');set('#battery-capacity',`${vehicle.batteryCapacity||75} kWh`);set('#charging-limit',`${vehicle.chargingLimit||80}%`);set('#dashboard-battery',`${vehicle.batteryLevel??68}%`);set('#dashboard-range',`Estimated range ${Math.round((Number(vehicle.batteryLevel??68)/100)*480)} km`);document.querySelector('#dashboard-battery-bar')?.style.setProperty('width',`${vehicle.batteryLevel??68}%`);
set('#dashboard-wallet-balance',Number(wallet.personal||0).toLocaleString());set('#wallet-currency',user.currency||'AMD');set('#dashboard-promo',`${Number(wallet.promo||0).toLocaleString()} ${user.currency||'AMD'}`);set('#auto-top-up',wallet.autoTopup?'Enabled':'Disabled');
const reservationCard=document.querySelector('#dashboard-reservation-card');if(reservation){reservationCard.hidden=false;set('#reservation-status',reservation.status==='active'?'Active':'Confirmed');set('#reservation-location',reservation.location||'Charging location');set('#reservation-address',reservation.address||'Yerevan, Armenia');const arrival=reservation.arrival||`${reservation.date||''}T${reservation.time||''}`;set('#reservation-arrival',arrival?new Date(arrival).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Not set');set('#reservation-charger',reservation.charger||'Assigned on arrival');set('#reservation-target',`${reservation.target||80}% battery`)}else{reservationCard.hidden=true;document.querySelector('#dashboard-no-reservation')?.removeAttribute('hidden')}
const activity=document.querySelector('#dashboard-activity-list');if(activity){activity.innerHTML=sessions.length?sessions.map(s=>`<div class="activity-item"><span class="list-icon">✓</span><div class="list-main"><strong>${s.location||'Charging station'}</strong><span>${new Date(s.completedAt||s.date||Date.now()).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})} · Completed</span></div><div class="activity-value">${Number(s.energy||0).toFixed(1)} kWh</div><div class="activity-value">${Math.max(1,Math.round(Number(s.duration||0)/60))} min</div><strong class="activity-value">${Number(s.cost||0).toLocaleString()} ${user.currency||'AMD'}</strong></div>`).join(''):'<div class="dashboard-empty-row">No completed sessions yet. Start charging to create your first activity.</div>'}
set('#sidebar-reservation-count',String(getActiveReservation()?1:0));const rb=document.querySelector('#sidebar-reservation-count');if(rb)rb.style.display=getActiveReservation()?'grid':'none';set('#sidebar-notification-count',String(unreadNotifications()));
document.querySelector('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});document.querySelectorAll('[data-coming-soon]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const toast=document.querySelector('#dashboard-toast');toast.textContent=`${link.dataset.comingSoon} will be connected after map navigation is integrated.`;toast.classList.add('is-visible');clearTimeout(window.dashboardToastTimer);window.dashboardToastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2400)}));
