import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{getWallet,getVehicles,getSessions,getUser,saveVehicles,syncCommonUi,readJson,writeJson}from'../core/app-state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='voltdrive_fleet_profile';
let profile=readJson(KEY,{mode:'corporate',company:'TML Consulting',monthlyLimit:40000,approvedStations:['Yerevan Mall EV Station','Republic Square Charge Hub','Dalma Garden Station']});
function toast(text){const n=$('#fleet-toast');n.textContent=text;n.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('is-visible'),2200)}
function fleetVehicles(){const list=getVehicles();return list.map((v,i)=>({...v,corporate:i===0||v.ownership==='Corporate'})).filter(v=>v.corporate)}
function render(){const wallet=getWallet(),vehicles=fleetVehicles(),sessions=getSessions().filter((_,i)=>i<4),used=Math.max(0,profile.monthlyLimit-Number(wallet.corporate||0));$('#corporate-balance').textContent=`${Number(wallet.corporate||0).toLocaleString()} AMD`;$('#budget-used').textContent=`${used.toLocaleString()} AMD`;$('#budget-bar').style.width=`${Math.min(100,used/profile.monthlyLimit*100)}%`;$('#fleet-summary').innerHTML=`<article><strong>${vehicles.length}</strong><span>Assigned vehicles</span></article><article><strong>${profile.approvedStations.length}</strong><span>Approved stations</span></article><article><strong>${Number(wallet.corporate||0).toLocaleString()} AMD</strong><span>Corporate balance</span></article><article><strong>${sessions.length}</strong><span>Work sessions this month</span></article>`;$('#fleet-vehicles').innerHTML=vehicles.map((v,i)=>`<article class="fleet-vehicle"><span class="fleet-vehicle__icon">◇</span><div><strong>${v.manufacturer||'Tesla'} ${v.model||'Model Y'}</strong><small>${v.registration||'No plate'} · ${v.connector||'CCS2'} · ${v.batteryLevel||68}% battery</small></div><span class="status-pill">${i===0?'Active':'Available'}</span>${i===0?'':`<button type="button" data-vehicle="${v.id}">Use vehicle</button>`}</article>`).join('')||'<p>No corporate vehicles assigned.</p>';$('#fleet-policy').innerHTML=[['Billing','Corporate balance first'],['Session limit','12,000 AMD per charge'],['Approved network','VoltDrive corporate stations'],['Charging window','06:00–23:00'],['Idle fee','Driver responsibility'],['Receipt sharing','Automatic to fleet manager']].map(([a,b])=>`<article><strong>${a}</strong><span>${b}</span></article>`).join('');$('#fleet-activity').innerHTML=(sessions.length?sessions:[{location:'Yerevan Mall EV Station',energy:31.4,cost:4120,status:'Completed'},{location:'Republic Square Charge Hub',energy:24.8,cost:3348,status:'Completed'}]).map(s=>`<article class="activity-row"><span class="fleet-vehicle__icon">ϟ</span><div><strong>${s.location||s.station||'VoltDrive station'}</strong><small>${Number(s.energy||s.energyDelivered||0).toFixed(1)} kWh · ${Number(s.cost||s.total||0).toLocaleString()} AMD</small></div><span class="status-pill">${s.status||'Completed'}</span></article>`).join('')}
$('#fleet-vehicles').addEventListener('click',e=>{const b=e.target.closest('[data-vehicle]');if(!b)return;saveVehicles(getVehicles(),b.dataset.vehicle);syncCommonUi();render();toast('Corporate vehicle selected.')});
$$('[data-profile]').forEach(b=>b.addEventListener('click',()=>{$$('[data-profile]').forEach(x=>x.classList.toggle('is-active',x===b));profile.mode=b.dataset.profile;writeJson(KEY,profile);toast(`${b.textContent} billing profile selected.`)}));
$('#download-report').addEventListener('click',()=>{const data={generatedAt:new Date().toISOString(),company:profile.company,driver:getUser(),sessions:getSessions(),corporateBalance:getWallet().corporate};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='voltdrive-corporate-expense-report.json';a.click();URL.revokeObjectURL(url);toast('Expense report downloaded.')});
$('#logout-button').addEventListener('click',()=>{clearSession();location.href='./login.html'});$('#menu-toggle').addEventListener('click',()=>{$('#sidebar').classList.toggle('is-open');$('#mobile-overlay').classList.toggle('is-visible')});$('#mobile-overlay').addEventListener('click',()=>{$('#sidebar').classList.remove('is-open');$('#mobile-overlay').classList.remove('is-visible')});
syncCommonUi();render();
