import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',vehicle:{manufacturer:'Tesla',model:'Model Y'}};
const locations={
'yerevan-mall':{name:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue, Yerevan',distance:1.4,eta:5,status:'available',available:4,total:6,power:150,price:120,reliability:98,reservationFee:500,idleFee:50,bays:8,access:'Enter from Arshakunyats Avenue and follow EV charging signs to parking level P1.',facilities:['24/7 access','Shopping mall','Restrooms','Coffee & food','Accessible parking','CCTV security'],chargers:[{id:'C-101',connector:'CCS2',power:150,status:'available'},{id:'C-102',connector:'CCS2',power:150,status:'available'},{id:'C-103',connector:'CCS2',power:120,status:'busy'},{id:'C-104',connector:'Type 2',power:22,status:'available'},{id:'C-105',connector:'Type 2',power:22,status:'available'},{id:'C-106',connector:'CCS2',power:150,status:'busy'}]},
'republic-square':{name:'Republic Square Charge Hub',address:'1 Republic Square, Yerevan',distance:2.8,eta:9,status:'busy',available:2,total:8,power:240,price:135,reliability:96,reservationFee:600,idleFee:60,bays:10,access:'Use the underground parking entrance from Amiryan Street. EV bays are on level B1.',facilities:['City center','24/7 access','Restrooms','Restaurants','CCTV security','Accessible parking'],chargers:[{id:'RS-201',connector:'CCS2',power:240,status:'busy'},{id:'RS-202',connector:'CCS2',power:240,status:'available'},{id:'RS-203',connector:'CCS2',power:180,status:'busy'},{id:'RS-204',connector:'CCS2',power:180,status:'available'},{id:'RS-205',connector:'Type 2',power:22,status:'busy'},{id:'RS-206',connector:'Type 2',power:22,status:'busy'},{id:'RS-207',connector:'CCS2',power:150,status:'busy'},{id:'RS-208',connector:'CCS2',power:150,status:'busy'}]},
'dalma':{name:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway, Yerevan',distance:4.2,eta:11,status:'available',available:6,total:8,power:120,price:115,reliability:97,reservationFee:400,idleFee:40,bays:10,access:'Enter the main parking area and follow green EV signs to zone D.',facilities:['Shopping mall','Food court','Restrooms','Wi-Fi','Family parking','CCTV security'],chargers:[{id:'DG-301',connector:'CCS2',power:120,status:'available'},{id:'DG-302',connector:'CCS2',power:120,status:'available'},{id:'DG-303',connector:'CCS2',power:120,status:'available'},{id:'DG-304',connector:'CCS2',power:120,status:'available'},{id:'DG-305',connector:'Type 2',power:22,status:'available'},{id:'DG-306',connector:'Type 2',power:22,status:'available'},{id:'DG-307',connector:'CCS2',power:120,status:'busy'},{id:'DG-308',connector:'CCS2',power:120,status:'busy'}]},
'northern-avenue':{name:'Northern Avenue Chargers',address:'10 Northern Avenue, Yerevan',distance:3.1,eta:10,status:'reserved',available:1,total:4,power:180,price:140,reliability:95,reservationFee:700,idleFee:70,bays:4,access:'Use the Northern Avenue underground parking entrance. Chargers are opposite elevator core B.',facilities:['Underground parking','Restaurants','Restrooms','24/7 security','City center','Accessible parking'],chargers:[{id:'NA-401',connector:'CCS2',power:180,status:'busy'},{id:'NA-402',connector:'CCS2',power:180,status:'available'},{id:'NA-403',connector:'CCS2',power:150,status:'busy'},{id:'NA-404',connector:'Type 2',power:22,status:'busy'}]},
'airport':{name:'Zvartnots Airport EV Hub',address:'Zvartnots International Airport',distance:11.8,eta:22,status:'available',available:8,total:12,power:350,price:150,reliability:99,reservationFee:800,idleFee:80,bays:14,access:'Follow signs for long-stay parking. EV fast chargers are in row A near the terminal shuttle stop.',facilities:['24/7 access','Airport terminal','Restrooms','Food & coffee','Wi-Fi','CCTV security'],chargers:Array.from({length:12},(_,i)=>({id:`ZA-${501+i}`,connector:i<8?'CCS2':'Type 2',power:i<4?350:i<8?180:22,status:i<8?'available':'busy'}))}
};
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)],set=(s,v)=>{const n=qs(s);if(n)n.textContent=v};
const params=new URLSearchParams(location.search),locationId=params.get('id')||'yerevan-mall',station=locations[locationId]||locations['yerevan-mall'];
set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase());set('#vehicle-selector',`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`);
set('#location-name',station.name);set('#location-address',station.address);set('#location-distance',`${station.distance} km away`);set('#location-eta',`${station.eta} min drive`);set('#summary-availability',`${station.available} of ${station.total}`);set('#summary-power',`${station.power} kW`);set('#summary-price',`${station.price} AMD`);set('#summary-reliability',`${station.reliability}%`);set('#price-energy',`${station.price} AMD/kWh`);set('#price-reservation',`${station.reservationFee} AMD`);set('#price-idle',`${station.idleFee} AMD/min`);set('#estimated-cost',`${(station.price*40).toLocaleString()} AMD`);set('#access-instructions',station.access);set('#bay-summary',`${station.bays} total bays`);
const status=qs('#location-status');status.textContent=station.status==='available'?'Available now':station.status==='busy'?'Limited availability':station.status==='reserved'?'Reservation recommended':'Offline';status.classList.add(station.status);
qs('#charger-list').innerHTML=station.chargers.map(c=>`<article class="charger-row"><div><h3>${c.id}</h3><p>${c.status==='available'?'Ready to charge':c.status==='busy'?'Currently in use':'Temporarily unavailable'}</p></div><div class="charger-spec"><strong>${c.connector}</strong><span>Connector</span></div><div class="charger-power"><strong>${c.power} kW</strong><span>Maximum power</span></div><span class="charger-badge ${c.status}">${c.status==='available'?'Available':c.status==='busy'?'Busy':'Offline'}</span></article>`).join('');
qs('#charger-select').innerHTML=station.chargers.map(c=>`<option value="${c.id}" ${c.status!=='available'?'disabled':''}>${c.id} · ${c.connector} · ${c.power} kW${c.status!=='available'?' · unavailable':''}</option>`).join('');
const bayStatuses=Array.from({length:station.bays},(_,i)=>i<station.available?'available':i===station.available?'reserved':'busy');qs('#parking-grid').innerHTML=bayStatuses.map((s,i)=>`<div class="parking-bay ${s}"><strong>Bay ${String(i+1).padStart(2,'0')}</strong><span>${s==='available'?'Available':s==='reserved'?'Reserved':'Occupied'}</span></div>`).join('');
const facilityIcons=['◷','⌂','♿','☕','◉','⌁'];qs('#facility-grid').innerHTML=station.facilities.map((f,i)=>`<div class="facility-item"><span>${facilityIcons[i%facilityIcons.length]}</span>${f}</div>`).join('');
function toast(message){const t=qs('#location-toast');t.textContent=message;t.classList.add('is-visible');clearTimeout(window.locationToastTimer);window.locationToastTimer=setTimeout(()=>t.classList.remove('is-visible'),2500)}
qs('#favorite-button').addEventListener('click',e=>{e.currentTarget.classList.toggle('is-active');e.currentTarget.textContent=e.currentTarget.classList.contains('is-active')?'♥':'♡';toast(e.currentTarget.classList.contains('is-active')?'Added to favorites':'Removed from favorites')});
['#reserve-button','#panel-reserve-button'].forEach(s=>qs(s).addEventListener('click',()=>{const charger=qs('#charger-select')?.value||'';location.href=`./reservation.html?id=${locationId}&charger=${encodeURIComponent(charger)}`}));qs('#navigate-button').addEventListener('click',()=>toast(`Navigation started to ${station.name}`));qs('#start-button').addEventListener('click',()=>toast('Select an available charger to start charging.'));qs('#waiting-list-button').addEventListener('click',()=>{location.href=`./waiting-list.html?id=${locationId}`});const feedbackButton=qs('#feedback-button');if(feedbackButton)feedbackButton.href=`./station-feedback.html?id=${locationId}`;
qs('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});qsa('[data-coming-soon]').forEach(n=>n.addEventListener('click',e=>{e.preventDefault();toast(`${n.dataset.comingSoon} will be added in a later stage.`)}));
