import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',vehicle:{manufacturer:'Tesla',model:'Model Y'}};
const FAVORITES_KEY='voltdrive_favorite_stations',RECENTS_KEY='voltdrive_recent_stations';
const readList=key=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const writeList=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const stations=[
{id:'yerevan-mall',name:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue',distance:1.4,status:'available',available:4,total:6,power:150,price:120,connector:'CCS2',reservable:true,x:30,y:35},
{id:'republic-square',name:'Republic Square Charge Hub',address:'1 Republic Square',distance:2.8,status:'busy',available:2,total:8,power:240,price:135,connector:'CCS2',reservable:true,x:61,y:23},
{id:'dalma',name:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway',distance:4.2,status:'available',available:6,total:8,power:120,price:115,connector:'CCS2',reservable:true,x:22,y:72},
{id:'northern-avenue',name:'Northern Avenue Chargers',address:'10 Northern Avenue',distance:3.1,status:'reserved',available:1,total:4,power:180,price:140,connector:'CCS2',reservable:true,x:70,y:52},
{id:'airport',name:'Zvartnots Airport EV Hub',address:'Zvartnots International Airport',distance:11.8,status:'available',available:8,total:12,power:350,price:150,connector:'CCS2',reservable:true,x:78,y:78},
{id:'komitas',name:'Komitas Community Charger',address:'49 Komitas Avenue',distance:5.6,status:'offline',available:0,total:2,power:50,price:95,connector:'CHAdeMO',reservable:false,x:46,y:14},
{id:'cascade',name:'Cascade Parking Charge',address:'10 Tamanyan Street',distance:4.4,status:'busy',available:1,total:5,power:22,price:90,connector:'Type 2',reservable:false,x:49,y:66}
];
let activeFilter='all',search='',connector='all',sort='distance',selectedId='yerevan-mall',view='map';
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const set=(s,v)=>{const n=qs(s);if(n)n.textContent=v};
set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase());set('#vehicle-selector',`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`);
const statusLabel={available:'Available',busy:'Limited',reserved:'Reserved',offline:'Offline'};
function filteredStations(){let result=stations.filter(s=>{const text=`${s.name} ${s.address} ${s.connector}`.toLowerCase();if(search&&!text.includes(search))return false;if(connector!=='all'&&s.connector!==connector)return false;if(activeFilter==='available'&&s.available<1)return false;if(activeFilter==='fast'&&s.power<150)return false;if(activeFilter==='reservable'&&!s.reservable)return false;return true});return result.sort((a,b)=>sort==='availability'?b.available-a.available:sort==='price'?a.price-b.price:sort==='power'?b.power-a.power:a.distance-b.distance)}
function render(){const data=filteredStations();set('#result-count',`${data.length} station${data.length===1?'':'s'}`);qs('#map-markers').innerHTML=data.map(s=>`<button class="station-marker ${s.status} ${s.id===selectedId?'is-selected':''}" style="left:${s.x}%;top:${s.y}%" data-station-id="${s.id}" aria-label="${s.name}"><span class="station-marker__pin"><span>ϟ</span></span></button>`).join('');qs('#station-results').innerHTML=data.length?data.map(s=>`<article class="station-card ${s.id===selectedId?'is-selected':''}" data-station-id="${s.id}"><div class="station-card__top"><div><div class="station-name-row"><h3>${s.name}</h3><button class="station-favorite" type="button" data-favorite-station="${s.id}" aria-label="Favorite">${readList(FAVORITES_KEY).includes(s.id)?'★':'☆'}</button></div><p>${s.address} · ${s.distance} km</p></div><span class="station-status ${s.status}">${statusLabel[s.status]}</span></div><div class="station-specs"><span>${s.connector}</span><span>Up to ${s.power} kW</span><span>${s.available}/${s.total} available</span>${s.reservable?'<span>Reservable</span>':''}</div><div class="station-card__bottom"><div><strong>${s.price} AMD/kWh</strong><br><span>${s.distance} km away</span></div><button class="station-action" type="button" data-open-station="${s.id}">View details →</button></div></article>`).join(''):'<div class="empty-stations">No stations match your filters.</div>';bindStationEvents()}
function bindStationEvents(){qsa('[data-favorite-station]').forEach(n=>n.addEventListener('click',e=>{e.stopPropagation();const id=n.dataset.favoriteStation,list=readList(FAVORITES_KEY),next=list.includes(id)?list.filter(x=>x!==id):[id,...list];writeList(FAVORITES_KEY,next);render();showToast(next.includes(id)?'Station added to favorites':'Station removed from favorites')}));qsa('[data-station-id]').forEach(n=>n.addEventListener('click',()=>{selectedId=n.dataset.stationId;render();const card=qs(`.station-card[data-station-id="${selectedId}"]`);card?.scrollIntoView({behavior:'smooth',block:'nearest'})}));qsa('[data-open-station]').forEach(n=>n.addEventListener('click',e=>{e.stopPropagation();writeList(RECENTS_KEY,[n.dataset.openStation,...readList(RECENTS_KEY).filter(x=>x!==n.dataset.openStation)].slice(0,5));location.href=`./location-details.html?id=${n.dataset.openStation}`}))}
function showToast(message){const t=qs('#map-toast');t.textContent=message;t.classList.add('is-visible');clearTimeout(window.mapToastTimer);window.mapToastTimer=setTimeout(()=>t.classList.remove('is-visible'),2500)}
qs('#station-search').addEventListener('input',e=>{search=e.target.value.trim().toLowerCase();render()});qs('#connector-filter').addEventListener('change',e=>{connector=e.target.value;render()});qs('#sort-select').addEventListener('change',e=>{sort=e.target.value;render()});qsa('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;qsa('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===b));render()}));qsa('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;qsa('[data-view]').forEach(x=>x.classList.toggle('is-active',x===b));qs('#map-layout').classList.toggle('is-list',view==='list')}));qs('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});qsa('[data-coming-soon]').forEach(n=>n.addEventListener('click',e=>{e.preventDefault();showToast(`${n.dataset.comingSoon} will be added in a later stage.`)}));render();