import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import { getSession, clearSession } from "../core/auth-storage.js";

const KEYS={notifications:"voltdrive_notifications",profile:"voltdrive_user",vehicle:"voltdrive_vehicle",vehicles:"voltdrive_vehicles",wallet:"voltdrive_wallet"};
const seed=[
{id:"NT-1008",type:"station",title:"Charger unavailable",message:"Charger 04 at Yerevan Mall EV Station went offline. Charger 02 is available as an alternative.",time:"5 min ago",timestamp:8,read:false,priority:"critical",action:{label:"View station",href:"./location-details.html?id=yerevan-mall"}},
{id:"NT-1007",type:"reservation",title:"Reservation starts soon",message:"Your reservation at Yerevan Mall EV Station begins today at 18:30. Arrival grace period is 10 minutes.",time:"18 min ago",timestamp:7,read:false,priority:"normal",action:{label:"View reservation",href:"./reservation.html"}},
{id:"NT-1006",type:"payment",title:"Payment completed",message:"6,800 AMD was successfully charged for session CS-0001542.",time:"42 min ago",timestamp:6,read:false,priority:"normal",action:{label:"View payment",href:"./activity.html?tab=payments"}},
{id:"NT-1005",type:"charging",title:"Charging completed",message:"Your Tesla Model Y reached 80%. 42.5 kWh was delivered in 42 minutes.",time:"Today, 10:57",timestamp:5,read:true,priority:"normal",action:{label:"View session",href:"./activity.html"}},
{id:"NT-1004",type:"charging",title:"Charging started",message:"Charging started on Charger 101, Connector CCS2. Current power is 118 kW.",time:"Today, 10:15",timestamp:4,read:true,priority:"normal",action:{label:"Session details",href:"./activity.html"}},
{id:"NT-1003",type:"reservation",title:"Reservation confirmed",message:"Reservation RSV-28419 is confirmed for Yerevan Mall EV Station.",time:"Yesterday, 16:24",timestamp:3,read:true,priority:"normal",action:{label:"Open reservation",href:"./reservation.html"}},
{id:"NT-1002",type:"payment",title:"Wallet top-up successful",message:"10,000 AMD was added to your personal wallet using Visa •••• 4242.",time:"3 Aug, 09:40",timestamp:2,read:true,priority:"normal",action:{label:"Open wallet",href:"./wallet.html"}},
{id:"NT-1001",type:"charging",title:"Alternative charger recommended",message:"Republic Square Hub is busy. Dalma Garden Station has 4 available 150 kW chargers nearby.",time:"2 Aug, 18:05",timestamp:1,read:true,priority:"normal",action:{label:"View alternatives",href:"./map.html"}}
];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let notifications=read(KEYS.notifications,seed);if(!Array.isArray(notifications)||!notifications.length)notifications=seed;write(KEYS.notifications,notifications);let filter="all";
function profile(){const user=read(KEYS.profile,null)||getSession()||{};const name=user.name||user.fullName||"VoltDrive Driver";$("#sidebar-name").textContent=name;$("#sidebar-email").textContent=user.email||"driver@voltdrive.am";$("#avatar").textContent=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"VD"}
function activeVehicle(){const list=read(KEYS.vehicles,[]);const legacy=read(KEYS.vehicle,null);const item=list.find(v=>v.isActive)||list[0]||legacy;$("#vehicle-selector").textContent=item?`${item.manufacturer||"Tesla"} ${item.model||"Model Y"}`:"Add vehicle"}
function wallet(){const value=read(KEYS.wallet,{personal:14500});$("#header-wallet-balance").textContent=`${Number(value.personal||14500).toLocaleString("en-US")} AMD`}
const icon={charging:"ϟ",reservation:"▣",payment:"▤",station:"!"};
const titleMap={all:"All notifications",unread:"Unread notifications",charging:"Charging updates",reservation:"Reservation updates",payment:"Payment updates",station:"Station updates"};
function counts(){const unread=notifications.filter(n=>!n.read).length;const critical=notifications.filter(n=>n.priority==="critical").length;const completed=notifications.filter(n=>n.title.toLowerCase().includes("completed")).length;const reservations=notifications.filter(n=>n.type==="reservation").length;$("#critical-count").textContent=critical;$("#unread-count").textContent=unread;$("#completed-count").textContent=completed;$("#reservation-count").textContent=reservations;$("#filter-all-count").textContent=notifications.length;$("#filter-unread-count").textContent=unread;["charging","reservation","payment","station"].forEach(type=>$("#filter-"+type+"-count").textContent=notifications.filter(n=>n.type===type).length);$("#sidebar-notification-count").textContent=unread;$("#sidebar-notification-count").style.display=unread?"grid":"none";$("#header-notification-dot").style.display=unread?"block":"none"}
function filtered(){let rows=filter==="all"?notifications:filter==="unread"?notifications.filter(n=>!n.read):notifications.filter(n=>n.type===filter);const sort=$("#notification-sort").value;rows=[...rows];if(sort==="oldest")rows.sort((a,b)=>a.timestamp-b.timestamp);else if(sort==="priority")rows.sort((a,b)=>(b.priority==="critical")-(a.priority==="critical")||b.timestamp-a.timestamp);else rows.sort((a,b)=>b.timestamp-a.timestamp);return rows}
function render(){const rows=filtered();$("#feed-title").textContent=titleMap[filter];$("#feed-subtitle").textContent=`${rows.length} update${rows.length===1?"":"s"}`;$("#notification-list").innerHTML=rows.map(item=>`<article class="notification-item ${item.read?"":"is-unread"} ${item.priority==="critical"?"is-critical":""}" data-notification-id="${item.id}"><span class="notification-icon notification-icon--${item.type}">${icon[item.type]}</span><div class="notification-copy"><div class="notification-copy__top"><h3>${item.title}</h3>${item.priority==="critical"?'<span class="priority-pill">Critical</span>':""}</div><p>${item.message}</p><div class="notification-meta"><span>${item.time}</span><span class="notification-tag">${item.type}</span><span>${item.read?"Read":"Unread"}</span></div></div><div class="notification-actions"><a class="notification-primary-action" href="./notification-details.html?id=${encodeURIComponent(item.id)}">Open details</a><button type="button" data-toggle-read="${item.id}" title="${item.read?"Mark unread":"Mark read"}">${item.read?"○":"✓"}</button><button type="button" data-delete-notification="${item.id}" title="Delete">×</button></div></article>`).join("")||'<div class="empty-notifications"><strong>No notifications here</strong><span>New updates will appear automatically.</span></div>';counts()}
let timer;function toast(message){const node=$("#notification-toast");node.textContent=message;node.classList.add("is-visible");clearTimeout(timer);timer=setTimeout(()=>node.classList.remove("is-visible"),2400)}
$$('[data-filter]').forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle("is-active",x===button));render()}));
$("#notification-sort").addEventListener("change",render);$("#notification-list").addEventListener("click",event=>{const toggle=event.target.closest("[data-toggle-read]");const remove=event.target.closest("[data-delete-notification]");if(toggle){notifications=notifications.map(n=>n.id===toggle.dataset.toggleRead?{...n,read:!n.read}:n);write(KEYS.notifications,notifications);render()}if(remove){notifications=notifications.filter(n=>n.id!==remove.dataset.deleteNotification);write(KEYS.notifications,notifications);render();toast("Notification removed.")}});
$("#mark-all-read").addEventListener("click",()=>{notifications=notifications.map(n=>({...n,read:true}));write(KEYS.notifications,notifications);render();toast("All notifications marked as read.")});
$("#notification-settings").addEventListener("click",()=>toast("Notification preferences will be available in Settings."));$$('[data-coming-soon]').forEach(button=>button.addEventListener("click",event=>{event.preventDefault();toast(`${button.dataset.comingSoon} will be added in the next stage.`)}));
$("#logout-button").addEventListener("click",()=>{clearSession();location.href="./login.html"});$("#menu-toggle").addEventListener("click",()=>{document.querySelector("#sidebar")?.classList.toggle("is-open");$("#mobile-overlay")?.classList.toggle("is-visible")});$("#mobile-overlay").addEventListener("click",()=>{document.querySelector("#sidebar")?.classList.remove("is-open");$("#mobile-overlay")?.classList.remove("is-visible")});
profile();activeVehicle();wallet();render();
