import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{getSession,clearSession}from'../core/auth-storage.js';

const KEYS={notifications:'voltdrive_notifications',profile:'voltdrive_user',vehicles:'voltdrive_vehicles',vehicle:'voltdrive_vehicle',wallet:'voltdrive_wallet'};
const $=selector=>document.querySelector(selector);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const params=new URLSearchParams(location.search);
const notificationId=params.get('id');
let notifications=read(KEYS.notifications,[]);
let notification=notifications.find(item=>item.id===notificationId)||notifications[0]||null;
const iconMap={charging:'ϟ',reservation:'▣',payment:'▤',station:'!'};

const detailMap={
station:{recommendationTitle:'Choose an available charger',recommendationCopy:'The originally selected charger is unavailable. Review the station or open nearby alternatives before you arrive.',context:[['Location','Yerevan Mall EV Station'],['Affected charger','Charger 04'],['Current status','Offline'],['Alternative','Charger 02 · 150 kW']],actions:[['View station','./location-details.html?id=yerevan-mall','primary'],['Find alternatives','./map.html','secondary']],timeline:[['Charger status changed','Charger 04 reported an offline state.'],['Alternative found','Charger 02 is available and compatible with the active vehicle.'],['Driver notified','Critical station update delivered immediately.']]},
reservation:{recommendationTitle:'Prepare for arrival',recommendationCopy:'Your reservation starts soon. Navigate to the location and check in before the grace period expires.',context:[['Reservation','RSV-28419'],['Start time','Today · 18:30'],['Grace period','10 minutes'],['Location','Yerevan Mall EV Station']],actions:[['Navigate & check in','./arrival.html','primary'],['View reservation','./reservation.html','secondary']],timeline:[['Reservation confirmed','The charger was reserved successfully.'],['Reminder sent','Arrival reminder delivered before the start time.'],['Next step','Check in at the station before the grace period ends.']]},
payment:{recommendationTitle:'Review the transaction',recommendationCopy:'Open the related payment or receipt to verify the amount, payment source and final status.',context:[['Amount','6,800 AMD'],['Session','CS-0001542'],['Payment status','Completed'],['Payment source','Visa •••• 4242']],actions:[['View payment','./activity.html?tab=payments','primary'],['Open wallet','./wallet.html','secondary']],timeline:[['Session completed','Final charging values were received.'],['Payment processed','The selected payment source was charged.'],['Receipt available','The transaction is available in Activity.']]},
charging:{recommendationTitle:'Review the charging session',recommendationCopy:'Open the session details to review delivered energy, duration, costs and the final charging state.',context:[['Session','CS-0001542'],['Vehicle','Tesla Model Y'],['Connector','CCS2'],['Status','Completed']],actions:[['View session','./activity.html','primary'],['Open receipt','./receipt.html','secondary']],timeline:[['Vehicle connected','Connector authentication completed.'],['Charging update','Session telemetry was updated.'],['Driver notified','The latest session state was delivered to the app.']]}
};

function profile(){const user=read(KEYS.profile,null)||getSession()||{};const name=user.name||user.fullName||'VoltDrive Driver';$('#sidebar-name').textContent=name;$('#sidebar-email').textContent=user.email||'driver@voltdrive.am';$('#avatar').textContent=name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()||'VD'}
function wallet(){const value=read(KEYS.wallet,{personal:14500});$('#header-wallet-balance').textContent=`${Number(value.personal||14500).toLocaleString('en-US')} AMD`}
function updateUnread(){const unread=notifications.filter(item=>!item.read).length;$('#sidebar-notification-count').textContent=unread;$('#sidebar-notification-count').style.display=unread?'grid':'none';$('#header-notification-dot').style.display=unread?'block':'none'}
function toast(message){const node=$('#notification-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('is-visible'),2400)}
function markRead(readState=true){if(!notification)return;notifications=notifications.map(item=>item.id===notification.id?{...item,read:readState}:item);notification={...notification,read:readState};write(KEYS.notifications,notifications);renderStatus();updateUnread()}
function renderStatus(){const status=$('#details-status');status.textContent=notification?.read?'Read':'Unread';status.classList.toggle('is-read',Boolean(notification?.read));$('#toggle-read').textContent=notification?.read?'Mark as unread':'Mark as read'}
function render(){if(!notification){$('#details-title').textContent='Notification not found';$('#details-message').textContent='This notification may have been deleted or the link is no longer valid.';$('#details-hero').classList.remove('is-critical');$('#context-grid').innerHTML='<div class="context-item"><span>Status</span><strong>Unavailable</strong></div>';$('#smart-actions').innerHTML='<a class="button button--primary" href="./notifications.html">Back to notifications</a>';$('#details-timeline').innerHTML='';return}
const details=detailMap[notification.type]||detailMap.charging;const icon=$('#details-icon');icon.textContent=iconMap[notification.type]||'◉';icon.className=`details-icon details-icon--${notification.type}`;$('#details-hero').classList.toggle('is-critical',notification.priority==='critical');$('#details-type').textContent=notification.type;$('#details-priority').hidden=notification.priority!=='critical';$('#details-title').textContent=notification.title;$('#details-message').textContent=notification.message;$('#details-time').textContent=notification.time;$('#details-id').textContent=notification.id;$('#recommendation-title').textContent=details.recommendationTitle;$('#recommendation-copy').textContent=details.recommendationCopy;$('#context-grid').innerHTML=details.context.map(([label,value])=>`<div class="context-item"><span>${label}</span><strong>${value}</strong></div>`).join('');$('#smart-actions').innerHTML=details.actions.map(([label,href,kind])=>`<a class="button button--${kind}" href="${href}">${label}</a>`).join('');$('#details-timeline').innerHTML=details.timeline.map(([title,copy])=>`<div class="timeline-item"><span class="timeline-dot"></span><div><strong>${title}</strong><span>${copy}</span></div></div>`).join('');$('#support-link').href=`./support.html?notification=${encodeURIComponent(notification.id)}&type=${encodeURIComponent(notification.type)}`;renderStatus();markRead(true)}

$('#toggle-read').addEventListener('click',()=>{markRead(!notification.read);toast(notification.read?'Marked as read.':'Marked as unread.')});
$('#snooze-notification').addEventListener('click',()=>{if(!notification)return;notifications=notifications.map(item=>item.id===notification.id?{...item,snoozedUntil:Date.now()+15*60*1000,read:true}:item);write(KEYS.notifications,notifications);toast('Notification snoozed for 15 minutes.');setTimeout(()=>location.href='./notifications.html',500)});
$('#delete-notification').addEventListener('click',()=>{if(!notification)return;notifications=notifications.filter(item=>item.id!==notification.id);write(KEYS.notifications,notifications);toast('Notification deleted.');setTimeout(()=>location.href='./notifications.html',500)});
$('#logout-button').addEventListener('click',()=>{clearSession();location.href='./login.html'});$('#menu-toggle').addEventListener('click',()=>{$('#sidebar')?.classList.toggle('is-open');$('#mobile-overlay')?.classList.toggle('is-visible')});$('#mobile-overlay').addEventListener('click',()=>{$('#sidebar')?.classList.remove('is-open');$('#mobile-overlay')?.classList.remove('is-visible')});
profile();wallet();updateUnread();render();
