import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{readJson,writeJson,KEYS,getActiveVehicle,getActiveReservation,getWallet,saveWallet,addTransaction,addNotification,syncCommonUi}from'../core/app-state.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();syncCommonUi();
const $=s=>document.querySelector(s);
const PARKING_KEY='voltdrive_parking_session';
const vehicle=getActiveVehicle();
const reservation=getActiveReservation();
const lastSession=readJson(KEYS.lastSession,null)||{};
const stored=readJson(PARKING_KEY,null);
const locationName=stored?.location||lastSession.location||reservation?.location||'Yerevan Mall EV Station';
const parking={id:stored?.id||`PK-${Date.now().toString().slice(-7)}`,location:locationName,bay:stored?.bay||reservation?.bay||'Bay 04',charger:stored?.charger||lastSession.charger||reservation?.charger||'C-101',energy:Number(stored?.energy??lastSession.energy??24.6),chargingCost:Number(stored?.chargingCost??lastSession.cost??2952),idleRate:Number(stored?.idleRate||50),graceSeconds:Number.isFinite(stored?.graceSeconds)?stored.graceSeconds:299,idleSeconds:Number(stored?.idleSeconds||0),idleCost:Number(stored?.idleCost||0),status:stored?.status||'grace',startedAt:stored?.startedAt||new Date().toISOString()};
let timer=null;
const set=(s,v)=>{const n=$(s);if(n)n.textContent=v};
const vehicleName=`${vehicle?.manufacturer||'Tesla'} ${vehicle?.model||'Model Y'}`;
set('#parking-location',`${parking.location} · ${parking.bay}`);set('#parking-vehicle',vehicleName);set('#parking-bay',parking.bay);set('#parking-charger',parking.charger);set('#parking-rate',`${parking.idleRate} AMD/min`);set('#side-location',parking.location);set('#side-energy',`${parking.energy.toFixed(1)} kWh`);set('#side-charge-cost',`${parking.chargingCost.toLocaleString()} AMD`);
function persist(){writeJson(PARKING_KEY,parking)}
function toast(message){const n=$('#parking-toast');n.textContent=message;n.classList.add('is-visible');clearTimeout(window.parkingToast);window.parkingToast=setTimeout(()=>n.classList.remove('is-visible'),2300)}
function render(){const idle=parking.status==='idle';const seconds=idle?parking.idleSeconds:Math.max(0,parking.graceSeconds);const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');set('#parking-countdown',`${mm}:${ss}`);set('#timer-label',idle?'Idle time':'Free parking remaining');set('#timer-note',idle?`${parking.idleRate} AMD is added for every minute`:'Idle fee starts when this timer reaches zero');set('#parking-status',idle?'Idle fee active':'No fee');set('#status-heading',idle?'Idle fee is being charged':'Grace period is active');set('#parking-title',idle?'Idle fee has started.':'Please move your vehicle.');set('#idle-cost',`${parking.idleCost.toLocaleString()} AMD`);set('#side-parking-cost',`${parking.idleCost.toLocaleString()} AMD`);set('#side-total',`${(parking.chargingCost+parking.idleCost).toLocaleString()} AMD`);$('#parking-status').className=`status-badge ${idle?'status-badge--error':'status-badge--success'}`;$('#idle-fee-banner').hidden=!idle;$('#parking-hero').classList.toggle('is-idle',idle);$('#parking-timer-card').classList.toggle('is-idle',idle);$('#parking-progress-bar').classList.toggle('is-idle',idle);const progress=idle?Math.min(100,(parking.idleSeconds/600)*100):Math.min(100,((299-parking.graceSeconds)/299)*100);$('#parking-progress-bar').style.width=`${progress}%`;persist()}
function beginIdle(){if(parking.status==='idle')return;parking.status='idle';parking.graceSeconds=0;addNotification({type:'parking',priority:'high',title:'Idle fee started',message:`Your vehicle is still in ${parking.bay} at ${parking.location}. Idle fees are now active.`,action:{label:'Open parking status',href:'./parking.html'}});render();toast('Idle fee preview activated.')}
function tick(){if(parking.status==='grace'){parking.graceSeconds=Math.max(0,parking.graceSeconds-1);if(parking.graceSeconds===0)beginIdle()}else if(parking.status==='idle'){parking.idleSeconds+=1;parking.idleCost=Math.ceil(parking.idleSeconds/60)*parking.idleRate}render()}
function completeParking(){clearInterval(timer);parking.status='completed';parking.completedAt=new Date().toISOString();persist();if(parking.idleCost>0){const wallet=getWallet();wallet.personal=Math.max(0,Number(wallet.personal||0)-parking.idleCost);saveWallet(wallet);addTransaction({type:'payment',title:'Idle parking fee',meta:`${parking.location} · ${parking.bay}`,amount:-parking.idleCost,parkingId:parking.id});addNotification({type:'payment',title:'Idle fee paid',message:`${parking.idleCost.toLocaleString()} AMD was charged after your vehicle left ${parking.bay}.`,action:{label:'View payments',href:'./activity.html?tab=payments'}})}else addNotification({type:'parking',title:'Parking completed',message:`You left ${parking.bay} before idle fees started.`,action:{label:'View activity',href:'./activity.html'}});syncCommonUi();$('.parking-layout').hidden=true;$('.parking-hero').hidden=true;$('#parking-complete').hidden=false;set('#parking-complete-copy',parking.idleCost?`${parking.idleCost.toLocaleString()} AMD in idle fees was charged.`:'No idle fee was charged.');window.scrollTo({top:0,behavior:'smooth'})}
$('#vehicle-removed-button').addEventListener('click',completeParking);
$('#extend-button').addEventListener('click',()=>{if(parking.status==='idle'){toast('Parking can no longer be extended after idle fees start.');return}parking.graceSeconds+=15*60;addTransaction({type:'payment',title:'Parking extension',meta:`${parking.location} · 15 minutes`,amount:-500,parkingId:parking.id});const wallet=getWallet();wallet.personal=Math.max(0,Number(wallet.personal||0)-500);saveWallet(wallet);addNotification({type:'parking',title:'Parking extended',message:'Your parking grace period was extended by 15 minutes for 500 AMD.',action:{label:'Open parking status',href:'./parking.html'}});syncCommonUi();render();toast('Parking extended by 15 minutes for 500 AMD.')});
$('#navigate-button').addEventListener('click',()=>toast(`Navigation started to ${parking.bay}.`));
$('#preview-idle-button').addEventListener('click',beginIdle);
$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});
render();timer=setInterval(tick,1000);
