import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();
const $=s=>document.querySelector(s);
const read=(key,fallback=null)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
const money=value=>`${Math.max(0,Math.round(Number(value)||0)).toLocaleString('en-US')} AMD`;
const dateTime=value=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const duration=seconds=>{const mins=Math.max(1,Math.round((Number(seconds)||0)/60));return `${Math.floor(mins/60)?`${Math.floor(mins/60)}h `:''}${mins%60}m`};
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',vehicle:{manufacturer:'Tesla',model:'Model Y'}};
const sessions=read('voltdrive_sessions',[]);
const last=read('voltdrive_last_session',null);
const params=new URLSearchParams(location.search);
const requested=params.get('id');
let session=sessions.find(item=>item.id===requested)||last||sessions[0]||{id:'CS-0001542',location:'Yerevan Mall EV Station',charger:'Charger 101',connector:'CCS2',energy:31.8,duration:2520,cost:4216,startBattery:34,battery:78,completedAt:new Date().toISOString(),paymentMethod:'Visa •••• 4242'};
const end=session.completedAt||session.date||new Date().toISOString();
const start=session.startedAt||new Date(new Date(end).getTime()-(Number(session.duration)||2520)*1000).toISOString();
const energy=Number(session.energy)||31.8;
const total=Number(session.cost)||4216;
const reservation=read('voltdrive_active_reservation',null);
const parking=read('voltdrive_parking_session',null);
const reservationFee=Number(session.reservationFee??reservation?.fee??500)||0;
const parkingFee=Number(session.parkingFee??parking?.extensionCost??0)||0;
const idleFee=Number(session.idleFee??parking?.idleCost??0)||0;
const connectionFee=Number(session.connectionFee??200)||0;
const discount=Number(session.discount??0)||0;
const vat=Math.round(total/6);
const energySubtotal=Math.max(0,total-reservationFee-parkingFee-idleFee-connectionFee+discount-vat);
const tariff=energy?Math.round(energySubtotal/energy):0;
const vehicle=session.vehicle||`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`;
const receiptNo=`RCP-${String(session.id||Date.now()).replace(/\D/g,'').slice(-7).padStart(7,'0')}`;
const transaction=session.transactionId||`PAY-${String(Date.now()).slice(-7)}`;
const set=(id,value)=>{const node=$(id);if(node)node.textContent=value};
set('#receipt-number',receiptNo);set('#receipt-date',dateTime(end));set('#session-id',session.id||'CS-0001542');set('#vehicle-name',vehicle);set('#location-name',session.location||'Yerevan Mall EV Station');set('#charger-name',`${session.charger||'Charger 101'} · ${session.connector||'CCS2'}`);set('#start-time',dateTime(start));set('#end-time',dateTime(end));set('#energy-delivered',`${energy.toFixed(1)} kWh`);set('#session-duration',duration(session.duration||2520));set('#energy-line-label',`Energy (${energy.toFixed(1)} kWh × ${tariff} AMD)`);set('#energy-line-value',money(energySubtotal));set('#connection-fee',money(connectionFee));set('#reservation-fee',money(reservationFee));set('#parking-fee',money(parkingFee));set('#idle-fee',money(idleFee));set('#discount-value',discount?`−${money(discount)}`:money(0));set('#vat-value',money(vat));set('#total-paid',money(total));set('#payment-method',session.paymentMethod||'Visa •••• 4242');set('#transaction-id',transaction);set('#billing-customer',user.name||'VoltDrive Driver');set('#billing-email',user.email||'driver@voltdrive.am');set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase());
const wallet=read('voltdrive_wallet',{personal:14500});set('#header-wallet',money(wallet.personal??wallet.balance??14500));
function toast(message){const node=$('#receipt-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(window.receiptToast);window.receiptToast=setTimeout(()=>node.classList.remove('is-visible'),2400)}
$('#print-receipt').addEventListener('click',()=>window.print());
$('#email-receipt').addEventListener('click',()=>toast(`Receipt sent to ${user.email||'your email'}.`));
$('#download-data').addEventListener('click',()=>{const data={receiptNumber:receiptNo,sessionId:session.id,issued:end,vehicle,location:session.location,charger:session.charger,connector:session.connector,energyKwh:energy,durationSeconds:session.duration,totalAMD:total,vatAMD:vat,paymentMethod:session.paymentMethod||'Visa •••• 4242',transactionId:transaction};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${receiptNo}.json`;a.click();URL.revokeObjectURL(url);toast('Receipt data downloaded.')});
$('#logout-button').addEventListener('click',()=>{clearSession();location.href='./login.html'});
