import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser}from'../core/auth-storage.js';
import{addNotification,syncCommonUi}from'../core/app-state.js';
import{initSidebar}from'../layout/sidebar.js';
initSidebar();syncCommonUi();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',vehicle:{manufacturer:'Tesla',model:'Model Y',connector:'CCS2'}};
const stations={
'yerevan-mall':{name:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue, Yerevan',price:120,reservationFee:500,idleFee:50,chargers:[['C-101','CCS2',150],['C-102','CCS2',150],['C-104','Type 2',22],['C-105','Type 2',22]],bays:8},
'republic-square':{name:'Republic Square Charge Hub',address:'1 Republic Square, Yerevan',price:135,reservationFee:600,idleFee:60,chargers:[['RS-202','CCS2',240],['RS-204','CCS2',180]],bays:10},
'dalma':{name:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway, Yerevan',price:115,reservationFee:400,idleFee:40,chargers:[['DG-301','CCS2',120],['DG-302','CCS2',120],['DG-305','Type 2',22]],bays:10},
'northern-avenue':{name:'Northern Avenue Chargers',address:'10 Northern Avenue, Yerevan',price:140,reservationFee:700,idleFee:70,chargers:[['NA-402','CCS2',180]],bays:4},
'airport':{name:'Zvartnots Airport EV Hub',address:'Zvartnots International Airport',price:150,reservationFee:800,idleFee:80,chargers:[['ZA-501','CCS2',350],['ZA-502','CCS2',350],['ZA-509','Type 2',22]],bays:14}
};
const params=new URLSearchParams(location.search),locationId=params.get('id')||'yerevan-mall',station=stations[locationId]||stations['yerevan-mall'];
let currentStep=1;
const vehicleName=`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`;
const connector=user.vehicle?.connector||'CCS2';
const set=(s,v)=>{const n=$(s);if(n)n.textContent=v};
set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase());set('#vehicle-selector',vehicleName);set('#selected-vehicle',vehicleName);set('#confirm-vehicle',vehicleName);set('#success-vehicle',vehicleName);set('#vehicle-connector',`${connector} compatible`);
set('#summary-location',station.name);set('#summary-address',station.address);set('#confirm-location',station.name);$('#back-to-location').href=`./location-details.html?id=${locationId}`;
set('#review-energy',`${station.price} AMD/kWh`);set('#review-reservation-fee',`${station.reservationFee} AMD`);set('#review-idle-fee',`${station.idleFee} AMD/min`);
$('#charger-select').innerHTML=station.chargers.map(c=>`<option value="${c[0]}">${c[0]} · ${c[1]} · ${c[2]} kW</option>`).join('');
$('#bay-select').innerHTML=Array.from({length:station.bays},(_,i)=>`<option value="Bay ${String(i+1).padStart(2,'0')}">Bay ${String(i+1).padStart(2,'0')}</option>`).join('');
const today=new Date();const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);$('#arrival-date').min=today.toISOString().slice(0,10);$('#arrival-date').value=tomorrow.toISOString().slice(0,10);$('#arrival-time').value='18:30';
function typeLabel(){const t=$('input[name="reservationType"]:checked').value;if(t==='charger')return `Charger ${$('#charger-select').value}`;if(t==='parking')return $('#bay-select').value;if(t==='vehicle')return `Charging for ${vehicleName}`;return 'Any available charger'}
function typeShort(){const t=$('input[name="reservationType"]:checked').value;return t==='charger'?'Specific charger':t==='parking'?'Parking bay':t==='vehicle'?'Vehicle reservation':'Any charger'}
function estimatedEnergy(){const target=Number($('#target').value);return Math.max(15,Math.round((target-40)*.95))}
function updateSummary(){const date=$('#arrival-date').value,time=$('#arrival-time').value;const arrival=date&&time?`${new Date(`${date}T${time}`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}, ${time}`:'Select date and time';const energy=estimatedEnergy();const charging=energy*station.price;set('#summary-type',typeShort());set('#summary-arrival',arrival);set('#summary-target',`${$('#target').value}%`);set('#summary-energy',`${energy} kWh`);set('#summary-charging-cost',`${charging.toLocaleString()} AMD`);set('#summary-reservation-fee',`${station.reservationFee.toLocaleString()} AMD`);set('#summary-total',`${(charging+station.reservationFee).toLocaleString()} AMD`)}
function updateConditional(){const t=$('input[name="reservationType"]:checked').value;$('#charger-field').hidden=t!=='charger';$('#bay-field').hidden=t!=='parking';$$('.choice-card').forEach(c=>c.classList.toggle('is-selected',c.querySelector('input').checked));updateSummary()}
function showStep(step){currentStep=step;$$('.reservation-step').forEach(n=>n.classList.toggle('is-active',Number(n.dataset.step)===step));$$('.progress-track span').forEach((n,i)=>n.classList.toggle('is-active',i<step));set('#step-count',`Step ${step} of 4`);$('#previous-button').hidden=step===1;$('#next-button').hidden=step===4;$('#confirm-button').hidden=step!==4;$('#form-error').textContent='';if(step===4){set('#confirm-type',typeLabel());const date=$('#arrival-date').value,time=$('#arrival-time').value;set('#confirm-arrival',`${new Date(`${date}T${time}`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}, ${time}`);set('#confirm-duration',$('#duration').selectedOptions[0].textContent);set('#confirm-target',`${$('#target').value}%`)}}
function validateStep(){if(currentStep===2&&(!$('#arrival-date').value||!$('#arrival-time').value)){set('#form-error','Choose an arrival date and time.');return false}if(currentStep===3&&!$('#terms-check').checked){set('#form-error','Accept the reservation conditions to continue.');return false}return true}
function toast(message){const t=$('#reservation-toast');t.textContent=message;t.classList.add('is-visible');clearTimeout(window.reservationToastTimer);window.reservationToastTimer=setTimeout(()=>t.classList.remove('is-visible'),2400)}
$$('input[name="reservationType"]').forEach(n=>n.addEventListener('change',updateConditional));['#charger-select','#bay-select','#arrival-date','#arrival-time','#duration','#target'].forEach(s=>$(s).addEventListener('change',updateSummary));
$('#next-button').addEventListener('click',()=>{if(validateStep())showStep(Math.min(4,currentStep+1))});$('#previous-button').addEventListener('click',()=>showStep(Math.max(1,currentStep-1)));
$('#reservation-form').addEventListener('submit',e=>{e.preventDefault();const number=`RSV-${String(Math.floor(100000+Math.random()*900000))}`;const code=String(Math.floor(100000+Math.random()*900000));const date=$('#arrival-date').value,time=$('#arrival-time').value;const reservation={number,locationId,location:station.name,address:station.address,type:typeLabel(),date,time,duration:$('#duration').value,target:$('#target').value,vehicle:vehicleName,status:'confirmed',accessCode:code,createdAt:new Date().toISOString()};localStorage.setItem('voltdrive_active_reservation',JSON.stringify(reservation));
try{const key='voltdrive_reservations';const list=JSON.parse(localStorage.getItem(key)||'[]');const normalized={id:reservation.number||reservation.id,status:reservation.status||'confirmed',locationId,location:station.name,address:station.address,arrival:`${reservation.date}T${reservation.time}`,duration:Number(reservation.duration)||60,target:Number(reservation.target)||80,type:reservation.type||typeShort(),vehicle:vehicleName,charger:reservation.charger||typeLabel(),bay:reservation.bay||'—',accessCode:reservation.accessCode||reservation.code||'742 918',fee:station.reservationFee,estimate:(estimatedEnergy()*station.price)+station.reservationFee};const next=[normalized,...list.filter(x=>x.id!==normalized.id)];localStorage.setItem(key,JSON.stringify(next));addNotification({type:'reservation',title:'Reservation confirmed',message:`${station.name} is reserved for ${date} at ${time}.`,action:{label:'View reservation',href:'./reservations.html'}});syncCommonUi();}catch(error){console.warn('Could not update reservations list',error)}set('#reservation-number',number);set('#access-code',code);set('#success-arrival',`${new Date(`${date}T${time}`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}, ${time}`);set('#success-description',`${station.name} is reserved for ${reservation.type.toLowerCase()}.`);$('.reservation-heading').hidden=true;$('.progress-track').hidden=true;$('.reservation-layout').hidden=true;$('#back-to-location').hidden=true;$('#reservation-success').hidden=false;window.scrollTo({top:0,behavior:'smooth'})});
$('#modify-reservation').addEventListener('click',()=>{$('#reservation-success').hidden=true;$('.reservation-heading').hidden=false;$('.progress-track').hidden=false;$('.reservation-layout').hidden=false;$('#back-to-location').hidden=false;showStep(1)});$('#navigation-after-booking').addEventListener('click',()=>{location.href='./arrival.html'});
$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});$$('[data-coming-soon]').forEach(n=>n.addEventListener('click',e=>{e.preventDefault();toast(`${n.dataset.comingSoon} will be added in a later stage.`)}));
updateConditional();updateSummary();showStep(1);
