import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import {clearSession,getStoredUser} from '../core/auth-storage.js';
import {syncCommonUi} from '../core/app-state.js';
import {initSidebar} from '../layout/sidebar.js';
initSidebar();syncCommonUi();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',vehicle:{manufacturer:'Tesla',model:'Model Y'}};
const STORAGE='voltdrive_reservations',LEGACY='voltdrive_active_reservation';
const now=new Date();
const iso=(offset,hour='18:30')=>{const d=new Date(now);d.setDate(d.getDate()+offset);return `${d.toISOString().slice(0,10)}T${hour}`};
const defaults=[
{id:'R-204918',status:'confirmed',locationId:'yerevan-mall',location:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue, Yerevan',arrival:iso(1),duration:60,target:80,type:'Any available charger',vehicle:'Tesla Model Y',charger:'Assigned on arrival',bay:'Bay 04',accessCode:'742 918',fee:500,estimate:4820},
{id:'R-198442',status:'completed',locationId:'republic-square',location:'Republic Square Charge Hub',address:'1 Republic Square, Yerevan',arrival:iso(-6,'14:10'),duration:45,target:80,type:'Specific charger',vehicle:'Tesla Model Y',charger:'RS-202',bay:'Bay 02',accessCode:'118 430',fee:600,estimate:3650},
{id:'R-188216',status:'cancelled',locationId:'dalma',location:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway, Yerevan',arrival:iso(-18,'10:00'),duration:60,target:90,type:'Parking bay',vehicle:'Tesla Model Y',charger:'Assigned on arrival',bay:'Bay 07',accessCode:'530 671',fee:400,estimate:5100},
{id:'R-177904',status:'no-show',locationId:'northern-avenue',location:'Northern Avenue Chargers',address:'10 Northern Avenue, Yerevan',arrival:iso(-32,'19:45'),duration:30,target:70,type:'Any available charger',vehicle:'Tesla Model Y',charger:'Assigned on arrival',bay:'—',accessCode:'310 882',fee:700,estimate:2900}
];
function normaliseLegacy(r){if(!r)return null;return{id:r.number||r.id||`R-${Date.now().toString().slice(-6)}`,status:r.status||'confirmed',locationId:r.locationId||'yerevan-mall',location:r.location||r.station||'Yerevan Mall EV Station',address:r.address||'34 Arshakunyats Avenue, Yerevan',arrival:r.arrival||`${r.date||new Date().toISOString().slice(0,10)}T${r.time||'18:30'}`,duration:Number(r.duration)||60,target:Number(r.target)||80,type:r.type||'Any available charger',vehicle:r.vehicle||`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`,charger:r.charger||'Assigned on arrival',bay:r.bay||'—',accessCode:r.accessCode||r.code||'742 918',fee:Number(r.fee)||500,estimate:Number(r.estimate)||4820}}
function load(){let list=[];try{list=JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{};let legacy=null;try{legacy=normaliseLegacy(JSON.parse(localStorage.getItem(LEGACY)||'null'))}catch{};if(!list.length)list=[...defaults];if(legacy&&!list.some(x=>x.id===legacy.id))list.unshift(legacy);save(list);return list}
function save(v){localStorage.setItem(STORAGE,JSON.stringify(v));const active=v.find(x=>['confirmed','active'].includes(x.status));if(active)localStorage.setItem(LEGACY,JSON.stringify(active));else localStorage.removeItem(LEGACY);syncCommonUi()}
let reservations=load(),activeTab='upcoming',selectedId=null,editingId=null;
const set=(s,v)=>{const n=$(s);if(n)n.textContent=v};
set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase());set('#vehicle-selector',`${user.vehicle?.manufacturer||'Tesla'} ${user.vehicle?.model||'Model Y'}`);
function category(r){if(['confirmed','active'].includes(r.status))return'upcoming';return r.status}
function fmtDate(v,opts={month:'short',day:'numeric',year:'numeric'}){return new Date(v).toLocaleDateString('en-US',opts)}
function fmtTime(v){return new Date(v).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}
function stats(){for(const [id,status] of [['#stat-upcoming','upcoming'],['#stat-completed','completed'],['#stat-cancelled','cancelled'],['#stat-noshow','no-show']])set(id,reservations.filter(r=>category(r)===status).length);set('#reservation-count',reservations.filter(r=>category(r)==='upcoming').length)}
function filtered(){const q=$('#reservation-search').value.trim().toLowerCase();return reservations.filter(r=>(activeTab==='all'||category(r)===activeTab)&&`${r.location} ${r.vehicle} ${r.accessCode} ${r.id}`.toLowerCase().includes(q)).sort((a,b)=>new Date(b.arrival)-new Date(a.arrival))}
function render(){stats();const rows=filtered();$('#reservation-list').innerHTML=rows.length?rows.map(r=>`<article class="reservation-card-item ${selectedId===r.id?'is-selected':''}" data-id="${r.id}"><div class="reservation-date-box"><span>${fmtDate(r.arrival,{month:'short'})}</span><strong>${fmtDate(r.arrival,{day:'2-digit'})}</strong></div><div class="reservation-card-main"><h3>${r.location}</h3><p>${fmtDate(r.arrival,{weekday:'short',month:'short',day:'numeric'})} · ${fmtTime(r.arrival)} · ${r.vehicle}</p></div><div class="reservation-card-meta"><span class="status-pill status-${r.status}">${r.status.replace('-', ' ')}</span><small>${r.type}</small></div></article>`).join(''):`<div class="empty-list"><h2>No reservations found</h2><p>Try another filter or create a new reservation.</p></div>`;$$('.reservation-card-item').forEach(n=>n.onclick=()=>{selectedId=n.dataset.id;render();renderDetail()});if(selectedId&&!reservations.some(r=>r.id===selectedId))selectedId=null;if(!selectedId&&rows[0]){selectedId=rows[0].id;renderDetail()}}
function qr(seed){return Array.from({length:81},(_,i)=>((i*7+seed.length*3+i%5)%4<2)?'<i></i>':'<span></span>').join('')}
function renderDetail(){const r=reservations.find(x=>x.id===selectedId);if(!r){$('#reservation-detail').innerHTML='<div class="empty-detail"><span>▣</span><h2>Select a reservation</h2><p>Details and available actions will appear here.</p></div>';return}const canEdit=category(r)==='upcoming';$('#reservation-detail').innerHTML=`<div class="detail-header"><span class="status-pill status-${r.status}">${r.status.replace('-',' ')}</span><h2>${r.location}</h2><p>${r.address}</p></div><div class="detail-content"><div class="detail-grid"><div class="detail-tile"><span>Arrival</span><strong>${fmtDate(r.arrival,{weekday:'short',month:'short',day:'numeric'})}, ${fmtTime(r.arrival)}</strong></div><div class="detail-tile"><span>Duration</span><strong>${r.duration} minutes</strong></div><div class="detail-tile"><span>Vehicle</span><strong>${r.vehicle}</strong></div><div class="detail-tile"><span>Target battery</span><strong>${r.target}%</strong></div><div class="detail-tile"><span>Charger</span><strong>${r.charger}</strong></div><div class="detail-tile"><span>Parking bay</span><strong>${r.bay}</strong></div><div class="detail-tile"><span>Reservation fee</span><strong>${r.fee.toLocaleString()} AMD</strong></div><div class="detail-tile"><span>Estimated total</span><strong>${r.estimate.toLocaleString()} AMD</strong></div></div>${canEdit?`<div class="access-panel"><span>Access code</span><strong>${r.accessCode}</strong><div class="qr-grid">${qr(r.id)}</div></div>`:''}<div class="detail-actions">${canEdit?`<a class="button button--primary" href="./arrival.html?reservation=${encodeURIComponent(r.id)}">Navigate</a><button class="button button--secondary" id="modify-reservation">Modify</button><button class="button button--secondary button--block danger-button" id="cancel-reservation">Cancel reservation</button>`:`<a class="button button--secondary button--block" href="./activity.html">View in activity</a>`}</div></div>`;if(canEdit){$('#modify-reservation').onclick=()=>openEdit(r);$('#cancel-reservation').onclick=()=>cancelReservation(r)}}
function toast(v){const n=$('#reservation-toast');n.textContent=v;n.classList.add('is-visible');clearTimeout(window.rt);window.rt=setTimeout(()=>n.classList.remove('is-visible'),2200)}
function openEdit(r){editingId=r.id;const d=new Date(r.arrival);$('#edit-date').value=d.toISOString().slice(0,10);$('#edit-date').min=new Date().toISOString().slice(0,10);$('#edit-time').value=d.toTimeString().slice(0,5);$('#edit-duration').value=String(r.duration);$('#edit-target').value=String(r.target);set('#edit-target-value',`${r.target}%`);$('#edit-modal').hidden=false}
function closeEdit(){$('#edit-modal').hidden=true;editingId=null}
function cancelReservation(r){if(!confirm(`Cancel reservation ${r.id}?`))return;r.status='cancelled';save(reservations);activeTab='cancelled';$$('.reservation-tabs button').forEach(x=>x.classList.toggle('is-active',x.dataset.tab===activeTab));render();renderDetail();toast('Reservation cancelled')}
$$('.reservation-tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;$$('.reservation-tabs button').forEach(x=>x.classList.toggle('is-active',x===b));selectedId=null;render()});$('#reservation-search').oninput=()=>{selectedId=null;render()};$('#edit-target').oninput=e=>set('#edit-target-value',`${e.target.value}%`);$('#close-edit').onclick=closeEdit;$('#cancel-edit').onclick=closeEdit;$('#edit-modal').onclick=e=>{if(e.target===$('#edit-modal'))closeEdit()};$('#edit-form').onsubmit=e=>{e.preventDefault();const r=reservations.find(x=>x.id===editingId);if(!r)return;const local=`${$('#edit-date').value}T${$('#edit-time').value}`;r.arrival=local;r.duration=Number($('#edit-duration').value);r.target=Number($('#edit-target').value);save(reservations);closeEdit();render();renderDetail();toast('Reservation updated')};$('#logout-button').onclick=()=>{clearSession();location.href='./login.html'};render();renderDetail();
