import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{addNotification,addSession,getActiveVehicle,getSessions,readJson,syncCommonUi,writeJson}from'../core/app-state.js';
const $=s=>document.querySelector(s);
const PREF_KEY='voltdrive_roaming_preferences';
const NETWORK_KEY='voltdrive_roaming_networks';
const defaults=[
{id:'charge-am',name:'Charge.am',logo:'CA',country:'Armenia',stations:18,available:11,price:165,preferred:true,connectors:['CCS2','Type 2']},
{id:'geocharge',name:'GeoCharge',logo:'GC',country:'Georgia',stations:34,available:20,price:190,preferred:true,connectors:['CCS2','CHAdeMO']},
{id:'caucasus-ev',name:'Caucasus EV',logo:'CE',country:'Regional',stations:27,available:8,price:210,preferred:false,connectors:['CCS2','Type 2']},
{id:'e-motion',name:'E-Motion Network',logo:'EM',country:'Armenia',stations:12,available:0,price:155,preferred:false,connectors:['Type 2']}
];
let prefs=readJson(PREF_KEY,{autoAuth:true,priceConfirm:true,showPartners:true,priceLimit:180});
let networks=readJson(NETWORK_KEY,defaults);
function toast(text){const n=$('#roaming-toast');n.textContent=text;n.classList.add('is-visible');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('is-visible'),2200)}
function renderSummary(){const total=networks.reduce((n,x)=>n+x.stations,0),available=networks.reduce((n,x)=>n+x.available,0),preferred=networks.filter(x=>x.preferred).length,avg=Math.round(networks.reduce((n,x)=>n+x.price,0)/networks.length);$('#roaming-summary').innerHTML=`<article><strong>${networks.length}</strong><span>Partner networks</span></article><article><strong>${total}</strong><span>Roaming stations</span></article><article><strong>${available}</strong><span>Chargers available now</span></article><article><strong>${avg} AMD</strong><span>Average roaming price / kWh</span></article>`}
function renderNetworks(){const filter=$('#network-filter').value;const list=networks.filter(n=>filter==='all'||filter==='available'&&n.available>0||filter==='preferred'&&n.preferred);$('#network-list').innerHTML=list.map(n=>`<article class="network-card"><span class="network-logo">${n.logo}</span><div class="network-card__main"><strong>${n.name}</strong><small>${n.country} · ${n.stations} stations · from ${n.price} AMD/kWh</small><div class="network-meta">${n.connectors.map(c=>`<span>${c}</span>`).join('')}<span>${n.preferred?'Preferred partner':'Standard partner'}</span></div></div><span class="status-pill ${n.available?'is-available':'is-busy'}">${n.available?`${n.available} available`:'No availability'}</span><button type="button" data-network="${n.id}">${n.preferred?'Remove favorite':'Add favorite'}</button></article>`).join('')||'<p>No partner networks match this filter.</p>'}
function renderActivity(){const roaming=getSessions().filter(s=>s.network||s.roaming).slice(0,4);const fallback=[{network:'Charge.am',station:'Northern Avenue Partner Hub',energy:28.6,cost:4719,status:'Settled'},{network:'GeoCharge',station:'Tbilisi Central EV',energy:41.2,cost:7828,status:'Settled'}];$('#roaming-activity').innerHTML=(roaming.length?roaming:fallback).map(s=>`<article class="activity-row"><span class="network-logo">◎</span><div><strong>${s.station||s.location||'Partner station'}</strong><small>${s.network||'Partner network'} · ${Number(s.energy||s.energyDelivered||0).toFixed(1)} kWh · ${Number(s.cost||s.total||0).toLocaleString()} AMD</small></div><span class="status-pill is-available">${s.status||'Settled'}</span></article>`).join('')}
function loadPrefs(){$('#auto-auth').checked=!!prefs.autoAuth;$('#price-confirm').checked=!!prefs.priceConfirm;$('#show-partners').checked=!!prefs.showPartners;$('#price-limit').value=String(prefs.priceLimit||180);$('#price-limit-value').textContent=`${prefs.priceLimit||180} AMD/kWh`}
$('#network-filter').addEventListener('change',renderNetworks);
$('#network-list').addEventListener('click',e=>{const b=e.target.closest('[data-network]');if(!b)return;const n=networks.find(x=>x.id===b.dataset.network);if(!n)return;n.preferred=!n.preferred;writeJson(NETWORK_KEY,networks);renderNetworks();toast(n.preferred?`${n.name} added to preferred networks.`:`${n.name} removed from preferred networks.`)});
$('#price-limit').addEventListener('input',e=>$('#price-limit-value').textContent=`${e.target.value} AMD/kWh`);
$('#save-preferences').addEventListener('click',()=>{prefs={autoAuth:$('#auto-auth').checked,priceConfirm:$('#price-confirm').checked,showPartners:$('#show-partners').checked,priceLimit:Number($('#price-limit').value)};writeJson(PREF_KEY,prefs);addNotification({type:'Settings',title:'Roaming preferences updated',message:`Partner charging confirmation threshold set to ${prefs.priceLimit} AMD/kWh.`});toast('Roaming preferences saved.')});
$('#preview-settlement').addEventListener('click',()=>{const vehicle=getActiveVehicle();addSession({network:'Charge.am',roaming:true,station:'Northern Avenue Partner Hub',vehicle:`${vehicle.manufacturer||'Tesla'} ${vehicle.model||'Model Y'}`,energy:18.4,cost:3036,status:'Settled',completedAt:new Date().toISOString()});addNotification({type:'Payment',title:'Roaming session settled',message:'Charge.am session was settled for 3,036 AMD and added to Activity.'});renderActivity();syncCommonUi();toast('Demo roaming settlement added.')});
$('#logout-button').addEventListener('click',()=>{clearSession();location.href='./login.html'});$('#menu-toggle').addEventListener('click',()=>{$('#sidebar').classList.toggle('is-open');$('#mobile-overlay').classList.toggle('is-visible')});$('#mobile-overlay').addEventListener('click',()=>{$('#sidebar').classList.remove('is-open');$('#mobile-overlay').classList.remove('is-visible')});
syncCommonUi();loadPrefs();renderSummary();renderNetworks();renderActivity();
