import{requireSession}from'../core/route-guard.js';if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';import{initSidebar}from'../layout/sidebar.js';import{getActiveVehicle,syncCommonUi,readJson,writeJson,addNotification}from'../core/app-state.js';
initSidebar();syncCommonUi();
const stations=[
{id:'airport',name:'Zvartnots Airport EV Hub',address:'Zvartnots International Airport',distance:11.8,detour:0.4,power:350,price:150,connector:'CCS2',available:8,total:12,eta:18,reservable:true},
{id:'yerevan-mall',name:'Yerevan Mall EV Station',address:'34 Arshakunyats Avenue',distance:1.4,detour:1.2,power:150,price:120,connector:'CCS2',available:4,total:6,eta:7,reservable:true},
{id:'dalma',name:'Dalma Garden Station',address:'3 Tsitsernakaberd Highway',distance:4.2,detour:2.1,power:120,price:115,connector:'CCS2',available:6,total:8,eta:10,reservable:true},
{id:'republic-square',name:'Republic Square Charge Hub',address:'1 Republic Square',distance:2.8,detour:3.4,power:240,price:135,connector:'CCS2',available:2,total:8,eta:12,reservable:true},
{id:'cascade',name:'Cascade Parking Charge',address:'10 Tamanyan Street',distance:4.4,detour:4.8,power:22,price:90,connector:'Type 2',available:1,total:5,eta:16,reservable:false}
];
const FAVORITES='voltdrive_favorite_stations',RECENTS='voltdrive_recent_stations';const $=s=>document.querySelector(s);const vehicle=getActiveVehicle();
$('#battery-level').textContent=`${vehicle.batteryLevel??68}%`;$('#estimated-range').textContent=`Estimated range ${Math.round((vehicle.batteryCapacity||75)*(vehicle.batteryLevel||68)/100*6.7)} km`;
function favorites(){return readJson(FAVORITES,[])}function recents(){return readJson(RECENTS,[])}function station(id){return stations.find(s=>s.id===id)}
function toast(message){const n=$('#route-toast');n.textContent=message;n.classList.add('is-visible');clearTimeout(window.rt);window.rt=setTimeout(()=>n.classList.remove('is-visible'),2400)}
function toggleFavorite(id){const list=favorites();const next=list.includes(id)?list.filter(x=>x!==id):[id,...list];writeJson(FAVORITES,next);render();toast(next.includes(id)?'Station added to favorites':'Station removed from favorites')}
function addRecent(id){writeJson(RECENTS,[id,...recents().filter(x=>x!==id)].slice(0,5))}
function renderCards(){const connector=$('#route-connector').value;const only=$('#only-available').checked;let data=stations.filter(s=>s.connector===connector&&(!only||s.available>0)).sort((a,b)=>(a.detour-a.available*.15)-(b.detour-b.available*.15)).slice(0,3);const fav=favorites();$('#route-results').innerHTML=data.map((s,i)=>`<article class="route-station"><div class="route-station__top"><div><small>${i===0?'Best match':'Alternative'}</small><h3>${s.name}</h3><p>${s.address}</p></div><button class="favorite-toggle" data-favorite="${s.id}" aria-label="Favorite">${fav.includes(s.id)?'★':'☆'}</button></div><div class="route-tags"><span>${s.detour} km detour</span><span>${s.eta} min away</span><span>${s.power} kW</span><span>${s.available}/${s.total} available</span><span>${s.price} AMD/kWh</span></div><div class="route-station__actions"><a href="./location-details.html?id=${s.id}" data-open="${s.id}">Details</a><a class="primary" href="${s.available?s.reservable?`./reservation.html?station=${s.id}`:`./charging.html?station=${s.id}`:`./waiting-list.html?station=${s.id}`}" data-open="${s.id}">${s.available?(s.reservable?'Reserve':'Charge'):'Join queue'}</a></div></article>`).join('')||'<div class="empty-mini">No compatible stations found for these filters.</div>';document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.favorite));document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>addRecent(a.dataset.open))}
function renderMini(){const mini=(ids,empty)=>ids.map(id=>station(id)).filter(Boolean).map(s=>`<div class="mini-item"><div><strong>${s.name}</strong><span>${s.address} · ${s.power} kW</span></div><a href="./location-details.html?id=${s.id}" data-open="${s.id}">Open →</a></div>`).join('')||`<div class="empty-mini">${empty}</div>`;$('#favorite-results').innerHTML=mini(favorites(),'No favorite stations yet. Use the star on a recommendation or on the map.');$('#recent-results').innerHTML=mini(recents(),'Stations you open will appear here.');document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>addRecent(a.dataset.open))}
function render(){renderCards();renderMini()}
$('#plan-route').onclick=()=>{const destination=$('#route-to').value.trim()||'Selected destination';const battery=Math.max(Number($('#arrival-target').value)+8,(vehicle.batteryLevel||68)-7);$('#route-distance').textContent='15.6 km';$('#route-time').textContent='24 min';$('#arrival-battery').textContent=`${battery}%`;addNotification({type:'station',title:'Route planned',message:`Charging options prepared for ${destination}.`});render();toast('Route recalculated using current demo conditions')};$('#route-connector').onchange=render;$('#only-available').onchange=render;$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});render();
