import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getSession}from"../core/auth-storage.js";
const KEYS={profile:"voltdrive_user",legacyProfile:"voltdrive_profile",vehicle:"voltdrive_vehicle",vehicles:"voltdrive_vehicles",wallet:"voltdrive_wallet",notifications:"voltdrive_notifications",region:"voltdrive_region",settings:"voltdrive_settings",devices:"voltdrive_devices"};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const defaults={phone:"+374 91 123456",company:"",language:"en",country:"AM",currency:"AMD",distanceUnit:"km",energyUnit:"kwh",timeFormat:"24",twoFactor:true,biometric:false,rfidAlert:true,locationHistory:true,usageAnalytics:true,recommendations:true,notificationChannels:{charging:{push:true,email:false,sms:false},reservation:{push:true,email:true,sms:false},payment:{push:true,email:true,sms:false},station:{push:true,email:false,sms:false}}};
let settings={...defaults,...read(KEYS.settings,{})};settings.notificationChannels={...defaults.notificationChannels,...(settings.notificationChannels||{})};
let profileData=read(KEYS.profile,null)||read(KEYS.legacyProfile,null)||getSession()||{};
let devices=read(KEYS.devices,[{id:"current",icon:"▣",name:"Chrome on Windows",detail:"Yerevan, Armenia · Current session",current:true},{id:"mobile",icon:"◇",name:"VoltDrive on iPhone",detail:"Last active 2 hours ago",current:false}]);write(KEYS.devices,devices);
function profile(){const name=profileData.name||profileData.fullName||"VoltDrive Driver";const email=profileData.email||"driver@voltdrive.am";const initials=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"VD";$("#sidebar-name").textContent=name;$("#sidebar-email").textContent=email;$("#avatar").textContent=initials;$("#profile-avatar").textContent=initials;$("#profile-summary-name").textContent=name;$("#profile-summary-email").textContent=email;$("#full-name").value=name;$("#email").value=email;$("#phone").value=settings.phone||"";$("#company").value=settings.company||""}
function activeVehicle(){const list=read(KEYS.vehicles,[]);const legacy=read(KEYS.vehicle,null);const item=list.find(v=>v.isActive)||list[0]||legacy;$("#vehicle-selector").textContent=item?`${item.manufacturer||"Tesla"} ${item.model||"Model Y"}`:"Add vehicle"}
function wallet(){const value=read(KEYS.wallet,{personal:14500});$("#header-wallet-balance").textContent=`${Number(value.personal||14500).toLocaleString("en-US")} ${settings.currency||"AMD"}`}
function notifications(){const list=read(KEYS.notifications,[]);const unread=list.filter(n=>!n.read).length;$("#sidebar-notification-count").textContent=unread;$("#sidebar-notification-count").style.display=unread?"grid":"none";$("#header-notification-dot").style.display=unread?"block":"none"}
function renderPreferences(){$("#language").value=settings.language;$("#country").value=settings.country;$("#currency").value=settings.currency;$("#distance-unit").value=settings.distanceUnit;$("#energy-unit").value=settings.energyUnit;$("#time-format").value=settings.timeFormat;$("#two-factor").checked=!!settings.twoFactor;$("#biometric").checked=!!settings.biometric;$("#rfid-alert").checked=!!settings.rfidAlert;$("#location-history").checked=!!settings.locationHistory;$("#usage-analytics").checked=!!settings.usageAnalytics;$("#recommendations").checked=!!settings.recommendations}
const notificationTypes=[{id:"charging",icon:"ϟ",title:"Charging updates",text:"Charging started, interrupted, completed and idle-fee alerts."},{id:"reservation",icon:"▣",title:"Reservation updates",text:"Confirmation, reminders, grace period and charger assignment."},{id:"payment",icon:"▤",title:"Payments and refunds",text:"Payment confirmation, failures, invoices and refunds."},{id:"station",icon:"⌖",title:"Station availability",text:"Unavailable chargers and recommended alternatives."}];
function renderNotificationPreferences(){$("#notification-preferences").innerHTML=notificationTypes.map(item=>{const c=settings.notificationChannels[item.id]||{};return`<article class="preference-row" data-notification-type="${item.id}"><div><span class="security-icon">${item.icon}</span><div><strong>${item.title}</strong><p>${item.text}</p></div></div><div class="channel-options"><label><input type="checkbox" data-channel="push" ${c.push?"checked":""}> Push</label><label><input type="checkbox" data-channel="email" ${c.email?"checked":""}> Email</label><label><input type="checkbox" data-channel="sms" ${c.sms?"checked":""}> SMS</label></div></article>`}).join("")}
function renderDevices(){$("#device-list").innerHTML=devices.map(device=>`<article class="device-item"><span>${device.icon}</span><div><strong>${device.name}${device.current?' <small>· Current</small>':""}</strong><small>${device.detail}</small></div>${device.current?"":`<button type="button" data-remove-device="${device.id}">Sign out</button>`}</article>`).join("")}
function setSecurityScore(){const count=[settings.twoFactor,settings.biometric,settings.rfidAlert].filter(Boolean).length;const label=count===3?"Excellent":count===2?"Good":"Needs attention";$("#security-score").textContent=label;$("#security-score").className=`status-pill ${count>=2?"status-pill--success":"status-pill--warning"}`}
let toastTimer;function toast(message){const node=$("#settings-toast");node.textContent=message;node.classList.add("is-visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("is-visible"),2400)}
function saveSettings(message="Settings saved."){write(KEYS.settings,settings);wallet();setSecurityScore();toast(message)}
$$('[data-section]').forEach(button=>button.addEventListener("click",()=>{$$('[data-section]').forEach(x=>x.classList.remove("is-active"));$$('[data-settings-panel]').forEach(x=>x.classList.remove("is-active"));button.classList.add("is-active");document.querySelector(`[data-settings-panel="${button.dataset.section}"]`).classList.add("is-active")}));
$("#profile-form").addEventListener("submit",event=>{event.preventDefault();const name=$("#full-name").value.trim();const email=$("#email").value.trim();if(name.length<2||!email.includes("@")){toast("Enter a valid name and email address.");return}profileData={...profileData,name,fullName:name,email};settings.phone=$("#phone").value.trim();settings.company=$("#company").value.trim();write(KEYS.profile,profileData);write(KEYS.legacyProfile,profileData);profile();saveSettings("Profile updated.")});
$("#preferences-form").addEventListener("submit",event=>{event.preventDefault();settings.language=$("#language").value;settings.country=$("#country").value;settings.currency=$("#currency").value;settings.distanceUnit=$("#distance-unit").value;settings.energyUnit=$("#energy-unit").value;settings.timeFormat=$("#time-format").value;write(KEYS.region,{country:settings.country,language:settings.language,currency:settings.currency});saveSettings("Regional preferences updated.")});
$("#save-notifications-button").addEventListener("click",()=>{$$('[data-notification-type]').forEach(row=>{const id=row.dataset.notificationType;settings.notificationChannels[id]={};row.querySelectorAll('[data-channel]').forEach(input=>settings.notificationChannels[id][input.dataset.channel]=input.checked)});saveSettings("Notification settings updated.")});
["two-factor","biometric","rfid-alert","location-history","usage-analytics","recommendations"].forEach(id=>$("#"+id).addEventListener("change",event=>{const map={"two-factor":"twoFactor","biometric":"biometric","rfid-alert":"rfidAlert","location-history":"locationHistory","usage-analytics":"usageAnalytics","recommendations":"recommendations"};settings[map[id]]=event.target.checked;saveSettings()}));
$("#password-form").addEventListener("submit",event=>{event.preventDefault();const current=$("#current-password").value;const next=$("#new-password").value;const confirm=$("#confirm-password").value;const message=$("#password-message");if(!current||next.length<8||next!==confirm){message.textContent="Check the current password and make sure the new passwords match.";message.style.color="var(--color-error)";return}message.textContent="Password updated successfully.";message.style.color="var(--color-success)";event.target.reset();toast("Password updated.")});
$("#device-list").addEventListener("click",event=>{const button=event.target.closest('[data-remove-device]');if(!button)return;devices=devices.filter(item=>item.id!==button.dataset.removeDevice);write(KEYS.devices,devices);renderDevices();toast("Device signed out.")});
$("#change-avatar-button").addEventListener("click",()=>toast("Photo upload will connect to the backend later."));$("#download-data-button").addEventListener("click",()=>{const data={profile:profileData,settings,vehicles:read(KEYS.vehicles,[]),wallet:read(KEYS.wallet,{}),notifications:read(KEYS.notifications,[])};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="voltdrive-account-data.json";a.click();URL.revokeObjectURL(url);toast("Account data downloaded.")});
function openDelete(){$("#delete-modal").classList.add("is-open");$("#delete-modal").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";$("#delete-confirmation").value="";$("#confirm-delete-button").disabled=true}function closeDelete(){$("#delete-modal").classList.remove("is-open");$("#delete-modal").setAttribute("aria-hidden","true");document.body.style.overflow=""}
$("#delete-account-button").addEventListener("click",openDelete);$$('[data-close-delete]').forEach(x=>x.addEventListener("click",closeDelete));$("#delete-confirmation").addEventListener("input",event=>$("#confirm-delete-button").disabled=event.target.value!=="DELETE");$("#confirm-delete-button").addEventListener("click",()=>{Object.keys(localStorage).filter(key=>key.startsWith("voltdrive_")).forEach(key=>localStorage.removeItem(key));clearSession();location.href="./register.html"});
$("#save-all-button").addEventListener("click",()=>saveSettings("All settings saved."));$("#logout-button").addEventListener("click",()=>{clearSession();location.href="./login.html"});$("#menu-toggle").addEventListener("click",()=>{$("#sidebar").classList.toggle("is-open");$("#mobile-overlay").classList.toggle("is-visible")});$("#mobile-overlay").addEventListener("click",()=>{$("#sidebar").classList.remove("is-open");$("#mobile-overlay").classList.remove("is-visible")});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeDelete()});
profile();activeVehicle();wallet();notifications();renderPreferences();renderNotificationPreferences();renderDevices();setSecurityScore();
