import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
import{addNotification,addTransaction,getUser,getWallet,readJson,saveWallet,syncCommonUi,writeJson}from'../core/app-state.js';
initSidebar();syncCommonUi();
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const user=getUser();let wallet=getWallet();let billing='monthly';let selectedProduct=null;
const SUB_KEY='voltdrive_subscription';const PACK_KEY='voltdrive_charging_package';
const plans=[
{id:'basic',name:'VoltDrive Basic',subtitle:'For occasional public charging',monthly:0,discount:0,features:['Standard charging tariffs','Station availability and reservations','Digital receipts and support']},
{id:'plus',name:'VoltDrive Plus',subtitle:'Best for regular city charging',monthly:2900,discount:10,featured:true,features:['10% discount on charging energy','No reservation fees','Priority waiting-list access','One free parking extension monthly']},
{id:'max',name:'VoltDrive Max',subtitle:'For frequent and long-distance drivers',monthly:6900,discount:18,features:['18% discount on charging energy','No reservation fees','Reduced idle fee for 30 minutes','Priority support','Two free parking extensions monthly']}
];
const packages=[
{id:'pack-50',name:'City Charge Pack',kwh:50,price:9500,validDays:60,label:'Best for commuting'},
{id:'pack-100',name:'Fast Charge Pack',kwh:100,price:17500,validDays:90,label:'Most popular'},
{id:'pack-250',name:'Road Trip Pack',kwh:250,price:39500,validDays:180,label:'Lowest price per kWh'}
];
const money=value=>`${Number(value||0).toLocaleString()} ${user.currency||'AMD'}`;
function toast(message){const node=$('#plans-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(window.plansToast);window.plansToast=setTimeout(()=>node.classList.remove('is-visible'),2300)}
function getSubscription(){return readJson(SUB_KEY,{planId:'plus',status:'active',billing:'monthly',autoRenew:true,renewalDate:'2026-09-06',startedAt:'2026-08-06'})}
function getPackage(){return readJson(PACK_KEY,{id:'pack-100',name:'Fast Charge Pack',purchasedKwh:100,remainingKwh:42,price:17500,autoRenew:false,expiresAt:'2026-09-30'})}
function planPrice(plan){if(billing==='annual'&&plan.monthly)return Math.round(plan.monthly*12*.85);return plan.monthly}
function renderActive(){const subscription=getSubscription(),plan=plans.find(item=>item.id===subscription.planId);const pack=getPackage();const cards=[];if(plan&&subscription.status==='active')cards.push(`<article class="active-product"><span class="active-product__icon">✦</span><div class="active-product__copy"><strong>${esc(plan.name)}</strong><span>${plan.discount}% charging discount · ${subscription.billing} billing · renews ${new Date(subscription.renewalDate).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><div class="active-product__actions"><button class="small-action" data-toggle-renewal="subscription" type="button">${subscription.autoRenew?'Auto-renew on':'Auto-renew off'}</button><button class="small-action" data-cancel-subscription type="button">Cancel</button></div></article>`);if(pack&&pack.remainingKwh>0)cards.push(`<article class="active-product"><span class="active-product__icon">ϟ</span><div class="active-product__copy"><strong>${esc(pack.name)}</strong><span>${Number(pack.remainingKwh).toFixed(0)} of ${pack.purchasedKwh} kWh remaining · expires ${new Date(pack.expiresAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><div class="active-product__actions"><button class="small-action" data-toggle-renewal="package" type="button">${pack.autoRenew?'Auto-renew on':'Auto-renew off'}</button></div></article>`);$('#active-products').innerHTML=cards.length?cards.join(''):'<article class="active-product"><span class="active-product__icon">＋</span><div class="active-product__copy"><strong>No active plans</strong><span>Select a membership or prepaid package below.</span></div></article>';bindActiveActions();renderUsage()}
function renderPlans(){$('#plan-grid').innerHTML=plans.map(plan=>{const active=getSubscription().status==='active'&&getSubscription().planId===plan.id;const price=planPrice(plan);return `<article class="plan-card${plan.featured?' is-featured':''}">${plan.featured?'<span class="plan-card__badge">MOST POPULAR</span>':''}<h3>${esc(plan.name)}</h3><p class="plan-card__subtitle">${esc(plan.subtitle)}</p><div class="plan-price"><strong>${price?money(price):'Free'}</strong><span>${price?billing==='annual'?'/ year':'/ month':''}</span></div><div class="plan-features">${plan.features.map(item=>`<div class="plan-feature">${esc(item)}</div>`).join('')}</div><button class="button ${active?'button--secondary':'button--primary'}" data-buy-plan="${plan.id}" type="button" ${active?'disabled':''}>${active?'Current plan':plan.id==='basic'?'Choose Basic':'Choose plan'}</button></article>`}).join('');$$('[data-buy-plan]').forEach(button=>button.addEventListener('click',()=>openPurchase('plan',button.dataset.buyPlan)))}
function renderPackages(){$('#package-grid').innerHTML=packages.map(pack=>`<article class="package-card"><div class="package-card__top"><div><strong>${esc(pack.name)}</strong><p>${esc(pack.label)}</p></div><span class="status-pill status-pill--blue">${pack.validDays} days</span></div><div class="package-kwh">${pack.kwh} kWh</div><p>${Math.round(pack.price/pack.kwh).toLocaleString()} AMD per kWh · used automatically before wallet funds.</p><div class="package-card__footer"><strong>${money(pack.price)}</strong><button class="button button--secondary button--small" data-buy-package="${pack.id}" type="button">Buy package</button></div></article>`).join('');$$('[data-buy-package]').forEach(button=>button.addEventListener('click',()=>openPurchase('package',button.dataset.buyPackage)))}
function renderUsage(){const pack=getPackage();const purchased=Number(pack?.purchasedKwh||0),remaining=Number(pack?.remainingKwh||0),used=Math.max(0,purchased-remaining),percent=purchased?remaining/purchased*100:0;$('#usage-remaining').textContent=`${remaining.toFixed(0)} kWh remaining`;$('#usage-purchased').textContent=`${purchased.toFixed(0)} kWh`;$('#usage-used').textContent=`${used.toFixed(0)} kWh`;$('#usage-saved').textContent=money(Math.round(used*50));$('#usage-expiry').textContent=pack?.expiresAt?`Expires ${new Date(pack.expiresAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:'No active package';$('#usage-progress-fill').style.width=`${Math.min(100,Math.max(0,percent))}%`}
function openPurchase(type,id){selectedProduct={type,id};const item=type==='plan'?plans.find(x=>x.id===id):packages.find(x=>x.id===id);const price=type==='plan'?planPrice(item):item.price;$('#modal-title').textContent=item.name;$('#purchase-summary').innerHTML=type==='plan'?`<div><span>Billing</span><strong>${billing}</strong></div><div><span>Charging discount</span><strong>${item.discount}%</strong></div><div><span>Total</span><strong>${money(price)}</strong></div>`:`<div><span>Energy</span><strong>${item.kwh} kWh</strong></div><div><span>Validity</span><strong>${item.validDays} days</strong></div><div><span>Total</span><strong>${money(price)}</strong></div>`;$('#plan-modal').classList.add('is-open');$('#plan-modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#plan-modal').classList.remove('is-open');$('#plan-modal').setAttribute('aria-hidden','true');selectedProduct=null}
function charge(price,source){if(source==='personal'){if(wallet.personal<price)return false;wallet.personal-=price}else if(source==='corporate'){if(wallet.corporate<price)return false;wallet.corporate-=price}saveWallet(wallet);return true}
$('#confirm-purchase').addEventListener('click',()=>{if(!selectedProduct)return;const source=$('#purchase-source').value,autoRenew=$('#purchase-autorenew').checked;const item=selectedProduct.type==='plan'?plans.find(x=>x.id===selectedProduct.id):packages.find(x=>x.id===selectedProduct.id);const price=selectedProduct.type==='plan'?planPrice(item):item.price;if(!charge(price,source)){toast('The selected balance is not sufficient.');return}if(selectedProduct.type==='plan'){const renewal=new Date();renewal.setMonth(renewal.getMonth()+(billing==='annual'?12:1));writeJson(SUB_KEY,{planId:item.id,status:'active',billing,autoRenew,startedAt:new Date().toISOString(),renewalDate:renewal.toISOString()});addTransaction({type:'payment',title:`${item.name} subscription`,meta:`${billing} plan · Just now`,amount:-price,status:'paid'});addNotification({type:'payment',title:'Subscription activated',message:`${item.name} is now active with ${item.discount}% charging discount.`,action:{label:'View plan',href:'./subscriptions.html'}})}else{const expiry=new Date();expiry.setDate(expiry.getDate()+item.validDays);writeJson(PACK_KEY,{id:item.id,name:item.name,purchasedKwh:item.kwh,remainingKwh:item.kwh,price:item.price,autoRenew,expiresAt:expiry.toISOString()});addTransaction({type:'payment',title:item.name,meta:`${item.kwh} kWh package · Just now`,amount:-price,status:'paid'});addNotification({type:'payment',title:'Charging package purchased',message:`${item.kwh} kWh was added to your account.`,action:{label:'View package',href:'./subscriptions.html'}})}syncCommonUi();renderActive();renderPlans();closeModal();toast(`${item.name} activated successfully.`)});
function bindActiveActions(){$('[data-cancel-subscription]')?.addEventListener('click',()=>{const current=getSubscription();writeJson(SUB_KEY,{...current,status:'cancelled',autoRenew:false});addNotification({type:'payment',title:'Subscription cancelled',message:'Your benefits remain available until the end of the current billing period.',action:{label:'View plans',href:'./subscriptions.html'}});renderActive();renderPlans();toast('Subscription cancelled at period end.')});$$('[data-toggle-renewal]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.toggleRenewal==='subscription'){const current=getSubscription();writeJson(SUB_KEY,{...current,autoRenew:!current.autoRenew})}else{const current=getPackage();writeJson(PACK_KEY,{...current,autoRenew:!current.autoRenew})}renderActive();toast('Automatic renewal updated.')}))}
$$('[data-billing]').forEach(button=>button.addEventListener('click',()=>{billing=button.dataset.billing;$$('[data-billing]').forEach(node=>node.classList.toggle('is-active',node===button));renderPlans()}));$$('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModal));$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});$('#menu-toggle')?.addEventListener('click',()=>document.body.classList.toggle('sidebar-open'));$('#mobile-overlay')?.addEventListener('click',()=>document.body.classList.remove('sidebar-open'));
renderActive();renderPlans();renderPackages();renderUsage();
