import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import { getSession, clearSession } from "../core/auth-storage.js";

const KEYS={tickets:"voltdrive_support_tickets",profile:"voltdrive_user",vehicle:"voltdrive_vehicle",vehicles:"voltdrive_vehicles",wallet:"voltdrive_wallet",notifications:"voltdrive_notifications"};
const faqs=[
{id:"faq-1",category:"charging",question:"Why will charging not start?",answer:"Confirm that the selected connector matches your vehicle, the cable is fully inserted and your payment method has enough balance for preauthorization. If the charger remains unavailable, try another connector or report the charger from this page."},
{id:"faq-2",category:"charging",question:"How do I stop a charging session safely?",answer:"Open Charge, choose Stop charging and wait until the charger confirms that power delivery has ended. Remove the cable only after the connector is unlocked."},
{id:"faq-3",category:"payment",question:"Why do I see a temporary 3,000 AMD hold?",answer:"VoltDrive may place a temporary preauthorization before charging. After the session, the final amount is charged and the unused portion of the hold is released by your bank."},
{id:"faq-4",category:"payment",question:"Where can I download a receipt or tax invoice?",answer:"Open Activity, select the relevant session or payment and use Download receipt or Download invoice in the detail panel."},
{id:"faq-5",category:"reservation",question:"What happens if I arrive after the grace period?",answer:"A reservation can expire after its grace period. The assigned charger or parking bay may then be released, and no-show rules may apply depending on the location."},
{id:"faq-6",category:"account",question:"How do I change my active vehicle?",answer:"Open Vehicles, select the required vehicle and choose Set active. Connector compatibility and charging estimates will then use that vehicle."}
];
const seedTickets=[
{id:"SUP-1042",type:"charger",subject:"Connector did not unlock",location:"Yerevan Mall EV Station",description:"Connector 02 remained locked after the session ended. The charger released it after a remote retry.",status:"waiting",created:"Today, 10:59",updated:"11 min ago",timeline:[{title:"Request created",text:"Diagnostic information was attached automatically.",time:"Today, 10:59"},{title:"Support response",text:"We sent a remote unlock command. Please confirm whether the cable is now released.",time:"Today, 11:04"}]},
{id:"SUP-0998",type:"payment",subject:"Receipt needed for session",location:"Not location-specific",description:"Requested a tax invoice for charging session CS-0001481.",status:"resolved",created:"1 Aug, 14:20",updated:"1 Aug, 14:37",timeline:[{title:"Request created",text:"Invoice requested from Activity.",time:"1 Aug, 14:20"},{title:"Resolved",text:"The invoice was generated and sent to the registered email.",time:"1 Aug, 14:37"}]}
];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let tickets=read(KEYS.tickets,seedTickets);if(!Array.isArray(tickets)||!tickets.length)tickets=seedTickets;write(KEYS.tickets,tickets);
let faqCategory="all";
function profile(){const user=read(KEYS.profile,null)||getSession()||{};const name=user.name||user.fullName||"VoltDrive Driver";$("#sidebar-name").textContent=name;$("#sidebar-email").textContent=user.email||"driver@voltdrive.am";$("#avatar").textContent=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"VD"}
function activeVehicle(){const list=read(KEYS.vehicles,[]);const legacy=read(KEYS.vehicle,null);const item=list.find(v=>v.isActive)||list[0]||legacy;$("#vehicle-selector").textContent=item?`${item.manufacturer||"Tesla"} ${item.model||"Model Y"}`:"Add vehicle"}
function wallet(){const value=read(KEYS.wallet,{personal:14500});$("#header-wallet-balance").textContent=`${Number(value.personal||14500).toLocaleString("en-US")} AMD`}
function notifications(){const list=read(KEYS.notifications,[]);const unread=list.filter(n=>!n.read).length;$("#sidebar-notification-count").textContent=unread;$("#sidebar-notification-count").style.display=unread?"grid":"none";$("#header-notification-dot").style.display=unread?"block":"none"}
function renderFaqs(){const query=$("#faq-search").value.trim().toLowerCase();const rows=faqs.filter(item=>(faqCategory==="all"||item.category===faqCategory)&&(!query||`${item.question} ${item.answer}`.toLowerCase().includes(query)));$("#faq-result-count").textContent=`${rows.length} helpful article${rows.length===1?"":"s"}`;$("#faq-list").innerHTML=rows.map(item=>`<article class="faq-item" data-faq-id="${item.id}"><button class="faq-question" type="button"><strong>${item.question}</strong><span>＋</span></button><div class="faq-answer">${item.answer}<span class="faq-category">${item.category}</span></div></article>`).join("")||'<div class="faq-empty">No matching help articles found.</div>'}
function statusLabel(status){return status==="waiting"?"Waiting for you":status.charAt(0).toUpperCase()+status.slice(1)}
function renderTickets(){const sorted=[...tickets].sort((a,b)=>String(b.id).localeCompare(String(a.id)));$("#ticket-list").innerHTML=sorted.slice(0,4).map(ticket=>`<button class="ticket-item" type="button" data-ticket-id="${ticket.id}"><div class="ticket-item__top"><h3>${ticket.subject}</h3><span class="ticket-status ticket-status--${ticket.status}">${statusLabel(ticket.status)}</span></div><p>${ticket.location}</p><div class="ticket-meta"><span>${ticket.id}</span><span>•</span><span>Updated ${ticket.updated}</span></div></button>`).join("")||'<div class="faq-empty">No support requests yet.</div>';$("#open-ticket-count").textContent=tickets.filter(t=>t.status!=="resolved").length}
function openModal(prefill){$("#ticket-modal").classList.add("is-open");$("#ticket-modal").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";if(prefill){$("#ticket-type").value=prefill;const names={charger:"Charger problem",payment:"Payment issue",reservation:"Reservation help",account:"Vehicle or account"};$("#ticket-subject").value=names[prefill]||""}setTimeout(()=>$("#ticket-subject").focus(),0)}
function closeModal(){$("#ticket-modal").classList.remove("is-open");$("#ticket-modal").setAttribute("aria-hidden","true");document.body.style.overflow="";$("#ticket-form-message").textContent=""}
function openDetail(id){const ticket=tickets.find(t=>t.id===id);if(!ticket)return;$("#detail-ticket-title").textContent=ticket.subject;$("#ticket-detail-content").innerHTML=`<div class="ticket-detail"><div class="ticket-detail__summary"><div><span>Ticket ID</span><strong>${ticket.id}</strong></div><div><span>Status</span><strong>${statusLabel(ticket.status)}</strong></div><div><span>Location</span><strong>${ticket.location}</strong></div></div><div class="ticket-description">${ticket.description}</div><div class="ticket-timeline">${ticket.timeline.map(entry=>`<article class="timeline-entry"><span></span><div><strong>${entry.title}</strong><p>${entry.text}</p><small>${entry.time}</small></div></article>`).join("")}</div></div>`;$("#ticket-detail-modal").classList.add("is-open");$("#ticket-detail-modal").setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeDetail(){$("#ticket-detail-modal").classList.remove("is-open");$("#ticket-detail-modal").setAttribute("aria-hidden","true");document.body.style.overflow=""}
let toastTimer;function toast(message){const node=$("#support-toast");node.textContent=message;node.classList.add("is-visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("is-visible"),2400)}
$("#faq-search").addEventListener("input",renderFaqs);$("#faq-category").addEventListener("change",event=>{faqCategory=event.target.value;renderFaqs()});$("#faq-list").addEventListener("click",event=>{const button=event.target.closest(".faq-question");if(!button)return;button.closest(".faq-item").classList.toggle("is-open")});
$("#new-ticket-button").addEventListener("click",()=>openModal());$$('[data-quick-help]').forEach(button=>button.addEventListener("click",()=>openModal(button.dataset.quickHelp)));$$('[data-close-modal]').forEach(button=>button.addEventListener("click",closeModal));$$('[data-close-detail]').forEach(button=>button.addEventListener("click",closeDetail));
$("#ticket-form").addEventListener("submit",event=>{event.preventDefault();const subject=$("#ticket-subject").value.trim();const description=$("#ticket-description").value.trim();if(subject.length<5||description.length<12){$("#ticket-form-message").textContent="Please add a clearer subject and description.";return}const now=new Date();const id=`SUP-${String(1100+tickets.length+1)}`;const ticket={id,type:$("#ticket-type").value,subject,location:$("#ticket-location").value,description,status:"open",created:"Just now",updated:"Just now",timeline:[{title:"Request created",text:"Your request was sent to VoltDrive Support.",time:"Just now"}]};tickets.unshift(ticket);write(KEYS.tickets,tickets);renderTickets();closeModal();event.target.reset();toast(`${id} was created successfully.`)});
$("#ticket-list").addEventListener("click",event=>{const item=event.target.closest("[data-ticket-id]");if(item)openDetail(item.dataset.ticketId)});$("#view-all-tickets").addEventListener("click",()=>toast(`${tickets.length} support requests loaded.`));$("#emergency-help").addEventListener("click",()=>toast("Stop charging and keep a safe distance from damaged equipment."));
$("#ticket-attachment").addEventListener("change",event=>{const file=event.target.files[0];if(file)toast(`${file.name} selected.`)});$$('[data-coming-soon]').forEach(button=>button.addEventListener("click",event=>{event.preventDefault();toast(`${button.dataset.comingSoon} will be added in the next stage.`)}));
$("#logout-button").addEventListener("click",()=>{clearSession();location.href="./login.html"});$("#menu-toggle").addEventListener("click",()=>{$("#sidebar").classList.toggle("is-open");$("#mobile-overlay").classList.toggle("is-visible")});$("#mobile-overlay").addEventListener("click",()=>{$("#sidebar").classList.remove("is-open");$("#mobile-overlay").classList.remove("is-visible")});document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeModal();closeDetail()}});
profile();activeVehicle();wallet();notifications();renderFaqs();renderTickets();
