import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser,saveUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
import{getSessions,readJson,syncCommonUi}from'../core/app-state.js';
initSidebar();syncCommonUi();
const $=selector=>document.querySelector(selector);const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let user=getStoredUser()||{};const fallback={id:'vehicle-primary',manufacturer:'Tesla',model:'Model Y',registration:'35 EV 777',batteryCapacity:75,batteryLevel:68,connector:'CCS2',chargingLimit:80,plugAndCharge:true,homeCharging:false,ownership:'personal'};let vehicles=Array.isArray(user.vehicles)&&user.vehicles.length?user.vehicles:[user.vehicle||fallback];const requestedId=new URLSearchParams(location.search).get('id');let vehicle=vehicles.find(item=>item.id===requestedId)||vehicles.find(item=>item.id===user.activeVehicleId)||vehicles[0];
const active=()=>vehicle.id===(user.activeVehicleId||vehicles[0]?.id);const set=(selector,value)=>{const node=$(selector);if(node)node.textContent=value};const money=value=>`${Number(value||0).toLocaleString()} ${user.currency||'AMD'}`;
function toast(message){const node=$('#vehicle-details-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(window.vehicleDetailsToast);window.vehicleDetailsToast=setTimeout(()=>node.classList.remove('is-visible'),2200)}
function paymentSource(){const prefs=readJson('voltdrive_payment_preferences',{promo:true,corporate:true,personal:true,card:true,digitalWallet:'Apple Pay'});const cards=readJson('voltdrive_cards',[]);if(prefs.promo)return{title:'Promo credits',meta:'Used first when available'};if(prefs.corporate)return{title:'Corporate balance',meta:'Company charging allowance'};if(prefs.personal)return{title:'Personal wallet',meta:'VoltDrive prepaid balance'};const card=cards.find(item=>item.isDefault)||cards[0];if(prefs.card)return{title:`${card?.brand||'Visa'} •••• ${card?.last4||'4242'}`,meta:'Default bank card'};return{title:prefs.digitalWallet||'No source selected',meta:'Digital wallet'} }
function sessionsForVehicle(){const all=getSessions();return all.filter(item=>item.vehicleId?item.vehicleId===vehicle.id:active()).slice(0,5)}
function render(){const name=`${vehicle.manufacturer||'Tesla'} ${vehicle.model||'Model Y'}`;document.title=`${name} — VoltDrive`;set('#vehicle-title',name);set('#vehicle-registration',vehicle.registration||'No registration');set('#battery-level',`${Number(vehicle.batteryLevel??68)}%`);set('#estimated-range',`${Math.round(Number(vehicle.batteryLevel??68)*4.55)} km`);set('#battery-capacity',`${Number(vehicle.batteryCapacity||75)} kWh capacity`);set('#charging-limit',`${Number(vehicle.chargingLimit||80)}% preferred limit`);$('#battery-fill').style.width=`${Math.min(100,Math.max(0,Number(vehicle.batteryLevel??68)))}%`;$('#active-state').textContent=active()?'Active vehicle':'Garage vehicle';$('#active-state').classList.toggle('is-inactive',!active());$('#set-active-button').hidden=active();
$('#vehicle-facts').innerHTML=[['Ownership',vehicle.ownership==='corporate'?'Corporate':'Personal'],['Primary connector',vehicle.connector||'CCS2'],['Plug & Charge',vehicle.plugAndCharge?'Enabled':'Disabled'],['Home charging',vehicle.homeCharging?'Configured':'Not configured']].map(([label,value])=>`<div class="vehicle-fact"><span>${label}</span><strong>${esc(value)}</strong></div>`).join('');
const connectors=[vehicle.connector||'CCS2',...(vehicle.connectors||[])].filter((item,index,list)=>item&&list.indexOf(item)===index);$('#connector-list').innerHTML=connectors.map((item,index)=>`<div class="connector-row"><div><strong>${esc(item)}</strong><span>${index===0?'Primary connector':'Compatible connector'}</span></div><span class="connector-status">Compatible</span></div>`).join('');
$('#plug-charge-panel').innerHTML=`<div class="plug-charge-card${vehicle.plugAndCharge?'':' is-disabled'}"><div><strong>${vehicle.plugAndCharge?'Certificate active':'Not enabled'}</strong><span>${vehicle.plugAndCharge?'Automatic identification available at compatible chargers.':'Enable it from Access methods.'}</span></div><span class="connector-status">${vehicle.plugAndCharge?'Ready':'Off'}</span></div>`;
$('#home-charging-panel').innerHTML=`<div class="config-row"><div><strong>${vehicle.homeCharging?'Home charger configured':'No home charger'}</strong><span>${vehicle.homeCharging?'Scheduled charging · Off-peak preference enabled':'Add a home charger and preferred schedule.'}</span></div><strong>${vehicle.homeCharging?'22 kW':'—'}</strong></div>`;
const source=paymentSource();$('#payment-source-panel').innerHTML=`<div class="payment-source-card"><div><strong>${esc(source.title)}</strong><span>${esc(source.meta)}</span></div><strong>Default</strong></div>`;
const sessions=sessionsForVehicle();$('#vehicle-history-list').innerHTML=sessions.length?`<div class="history-list">${sessions.map(item=>`<div class="history-row"><div><strong>${esc(item.location||'Charging station')}</strong><span>${new Date(item.completedAt||item.date||Date.now()).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span></div><div><strong>${Number(item.energy||0).toFixed(1)} kWh</strong><span>Energy</span></div><div><strong>${money(item.cost)}</strong><span>Cost</span></div><div><strong>${esc(item.status||'completed')}</strong><span>Status</span></div></div>`).join('')}</div>`:'<div class="history-empty">No charging sessions recorded for this vehicle yet.</div>';
}
$('#set-active-button').addEventListener('click',()=>{user={...user,activeVehicleId:vehicle.id,vehicle,vehicles};saveUser(user);syncCommonUi();render();toast(`${vehicle.manufacturer} ${vehicle.model} is now active.`)});
$('#home-config-button').addEventListener('click',()=>{vehicle={...vehicle,homeCharging:!vehicle.homeCharging};vehicles=vehicles.map(item=>item.id===vehicle.id?vehicle:item);user={...user,vehicles,vehicle:active()?vehicle:user.vehicle};saveUser(user);render();toast(vehicle.homeCharging?'Home charging configured.':'Home charging disabled.')});
$('#logout-button')?.addEventListener('click',()=>{clearSession();location.href='./login.html'});render();
