import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import{clearSession,getStoredUser,saveUser}from'../core/auth-storage.js';
import{initSidebar}from'../layout/sidebar.js';
import{syncCommonUi}from'../core/app-state.js';
initSidebar();syncCommonUi();
const fallbackVehicle={id:'vehicle-primary',manufacturer:'Tesla',model:'Model Y',registration:'35 EV 777',batteryCapacity:75,batteryLevel:68,connector:'CCS2',chargingLimit:80,plugAndCharge:true,homeCharging:false,ownership:'personal'};
let user=getStoredUser()||{name:'VoltDrive Driver',email:'driver@voltdrive.am',currency:'AMD',vehicle:fallbackVehicle};
function normaliseVehicle(vehicle,index=0){return{id:vehicle.id||`vehicle-${Date.now()}-${index}`,manufacturer:vehicle.manufacturer||'Tesla',model:vehicle.model||'Model Y',registration:vehicle.registration||'35 EV 777',batteryCapacity:Number(vehicle.batteryCapacity)||75,batteryLevel:Number(vehicle.batteryLevel??68),connector:vehicle.connector||'CCS2',chargingLimit:Number(vehicle.chargingLimit)||80,plugAndCharge:Boolean(vehicle.plugAndCharge),homeCharging:Boolean(vehicle.homeCharging),ownership:vehicle.ownership||'personal'}}
let vehicles=(Array.isArray(user.vehicles)&&user.vehicles.length?user.vehicles:[user.vehicle||fallbackVehicle]).map(normaliseVehicle);
let activeVehicleId=user.activeVehicleId||vehicles[0].id;
const grid=document.querySelector('#vehicle-grid');const empty=document.querySelector('#garage-empty');const search=document.querySelector('#vehicle-search');const ownershipFilter=document.querySelector('#ownership-filter');const modal=document.querySelector('#vehicle-modal');const form=document.querySelector('#garage-vehicle-form');
const set=(selector,value)=>{const node=document.querySelector(selector);if(node)node.textContent=value};
set('#sidebar-name',user.name||'VoltDrive Driver');set('#sidebar-email',user.email||'driver@voltdrive.am');set('#avatar',(user.name||'VD').split(/\s+/).map(value=>value[0]).join('').slice(0,2).toUpperCase());
function activeVehicle(){return vehicles.find(vehicle=>vehicle.id===activeVehicleId)||vehicles[0]}
function persist(){const active=activeVehicle();user={...user,vehicles,activeVehicleId,vehicle:active};saveUser(user);syncCommonUi();updateHeader();updateSummary()}
function updateHeader(){const active=activeVehicle();set('#vehicle-selector',`${active.manufacturer} ${active.model}`)}
function updateSummary(){const active=activeVehicle();set('#vehicle-count',String(vehicles.length));set('#active-vehicle-summary',`${active.manufacturer} ${active.model}`);set('#average-battery',`${Math.round(vehicles.reduce((sum,item)=>sum+item.batteryLevel,0)/Math.max(vehicles.length,1))}%`);set('#plug-charge-count',`${vehicles.filter(item=>item.plugAndCharge).length} enabled`)}
function card(vehicle){const active=vehicle.id===activeVehicleId;return`<article class="garage-card${active?' is-active':''}" data-vehicle-id="${vehicle.id}"><div class="garage-card__top"><div class="garage-card__identity"><span class="garage-card__icon">◇</span><div><h2>${escapeHtml(vehicle.manufacturer)} ${escapeHtml(vehicle.model)}</h2><div class="garage-card__plate">${escapeHtml(vehicle.registration)}</div></div></div><div class="garage-card__badges">${active?'<span class="vehicle-badge vehicle-badge--active">Active vehicle</span>':''}<span class="vehicle-badge">${vehicle.ownership==='corporate'?'Corporate':'Personal'}</span>${vehicle.plugAndCharge?'<span class="vehicle-badge">Plug & Charge</span>':''}</div></div><div class="garage-card__battery"><strong>${vehicle.batteryLevel}%</strong><div class="battery-bar"><i style="width:${vehicle.batteryLevel}%"></i></div><span>Current battery</span></div><div class="garage-card__metrics"><div class="garage-metric"><span>Battery</span><strong>${vehicle.batteryCapacity} kWh</strong></div><div class="garage-metric"><span>Connector</span><strong>${escapeHtml(vehicle.connector)}</strong></div><div class="garage-metric"><span>Charge limit</span><strong>${vehicle.chargingLimit}%</strong></div><div class="garage-metric"><span>Home charging</span><strong>${vehicle.homeCharging?'Configured':'Not set'}</strong></div></div><div class="garage-card__actions"><div>${active?'':'<button class="garage-action" type="button" data-action="activate">Set active</button>'}<button class="garage-action" type="button" data-action="details">View details</button><button class="garage-action" type="button" data-action="edit">Edit</button></div>${vehicles.length>1?'<button class="garage-action garage-action--danger" type="button" data-action="delete">Remove</button>':''}</div></article>`}
function render(){const term=search.value.trim().toLowerCase();const ownership=ownershipFilter.value;const filtered=vehicles.filter(vehicle=>{const haystack=`${vehicle.manufacturer} ${vehicle.model} ${vehicle.registration} ${vehicle.connector}`.toLowerCase();return(!term||haystack.includes(term))&&(ownership==='all'||vehicle.ownership===ownership)});grid.innerHTML=filtered.map(card).join('');empty.hidden=filtered.length>0}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function openModal(vehicle=null){form.reset();form.elements.vehicleId.value=vehicle?.id||'';form.elements.manufacturer.value=vehicle?.manufacturer||'Tesla';form.elements.model.value=vehicle?.model||'Model Y';form.elements.registration.value=vehicle?.registration||'35 EV 777';form.elements.batteryCapacity.value=vehicle?.batteryCapacity||75;form.elements.batteryLevel.value=vehicle?.batteryLevel??68;form.elements.chargingLimit.value=vehicle?.chargingLimit||80;form.elements.connector.value=vehicle?.connector||'CCS2';form.elements.ownership.value=vehicle?.ownership||'personal';form.elements.plugAndCharge.checked=vehicle?.plugAndCharge??true;form.elements.homeCharging.checked=vehicle?.homeCharging??false;set('#vehicle-modal-title',vehicle?'Edit vehicle':'Add vehicle');modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function toast(message){const node=document.querySelector('#vehicle-toast');node.textContent=message;node.classList.add('is-visible');clearTimeout(window.vehicleToastTimer);window.vehicleToastTimer=setTimeout(()=>node.classList.remove('is-visible'),2300)}
document.querySelector('#add-vehicle-button').addEventListener('click',()=>openModal());document.querySelector('#vehicle-modal-close').addEventListener('click',closeModal);document.querySelector('#vehicle-modal-backdrop').addEventListener('click',closeModal);document.querySelector('#cancel-vehicle-button').addEventListener('click',closeModal);search.addEventListener('input',render);ownershipFilter.addEventListener('change',render);
form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const id=String(data.get('vehicleId')||'');const vehicle=normaliseVehicle({id:id||`vehicle-${Date.now()}`,manufacturer:String(data.get('manufacturer')).trim(),model:String(data.get('model')).trim(),registration:String(data.get('registration')).trim(),batteryCapacity:Number(data.get('batteryCapacity')),batteryLevel:Number(data.get('batteryLevel')),chargingLimit:Number(data.get('chargingLimit')),connector:String(data.get('connector')),ownership:String(data.get('ownership')),plugAndCharge:form.elements.plugAndCharge.checked,homeCharging:form.elements.homeCharging.checked});if(id){vehicles=vehicles.map(item=>item.id===id?vehicle:item);toast('Vehicle updated.')}else{vehicles.push(vehicle);toast('Vehicle added to your garage.')}persist();render();closeModal()});
grid.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const article=button.closest('[data-vehicle-id]');const id=article?.dataset.vehicleId;const vehicle=vehicles.find(item=>item.id===id);if(!vehicle)return;if(button.dataset.action==='activate'){activeVehicleId=id;persist();render();toast(`${vehicle.manufacturer} ${vehicle.model} is now active.`)}if(button.dataset.action==='details')window.location.href=`./vehicle-details.html?id=${encodeURIComponent(vehicle.id)}`;if(button.dataset.action==='edit')openModal(vehicle);if(button.dataset.action==='delete'){if(!confirm(`Remove ${vehicle.manufacturer} ${vehicle.model} from your garage?`))return;vehicles=vehicles.filter(item=>item.id!==id);if(activeVehicleId===id)activeVehicleId=vehicles[0].id;persist();render();toast('Vehicle removed.')}});
document.querySelector('#logout-button')?.addEventListener('click',()=>{clearSession();window.location.href='./login.html'});document.querySelectorAll('[data-coming-soon]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();toast(`${link.dataset.comingSoon} will be added in the next stage.`)}));
persist();render();
