import{requireSession}from'../core/route-guard.js';
if(!requireSession())throw new Error('Authentication required');
import { getSession, clearSession } from "../core/auth-storage.js";
import {addNotification,syncCommonUi} from "../core/app-state.js";

const KEYS={wallet:"voltdrive_wallet",cards:"voltdrive_cards",transactions:"voltdrive_wallet_transactions",vehicle:"voltdrive_vehicle",vehicles:"voltdrive_vehicles",profile:"voltdrive_user",payment:"voltdrive_payment_method",preferences:"voltdrive_payment_preferences",disputes:"voltdrive_payment_disputes"};
const defaults={wallet:{personal:14500,corporate:25000,promo:2000,autoTopup:true,threshold:5000,topupAmount:10000},cards:[{id:"card-4242",brand:"VISA",last4:"4242",expiry:"12/30",holder:"VoltDrive Driver",isDefault:true}],transactions:[{id:"TX-1034",type:"payment",title:"Charging payment",meta:"Yerevan Mall EV Station · Today",amount:-6800},{id:"TX-1033",type:"topup",title:"Wallet top-up",meta:"Visa •••• 4242 · 3 Aug",amount:10000},{id:"TX-1032",type:"payment",title:"Reservation fee",meta:"Republic Square Hub · 2 Aug",amount:-500},{id:"TX-1031",type:"refund",title:"Charging refund",meta:"Session CS-0001498 · 31 Jul",amount:1200},{id:"TX-1030",type:"payment",title:"Charging payment",meta:"Dalma Garden Station · 29 Jul",amount:-4250}]};
const money=value=>`${Number(value).toLocaleString("en-US")} AMD`;
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let wallet=read(KEYS.wallet,defaults.wallet);let cards=read(KEYS.cards,[]);let transactions=read(KEYS.transactions,defaults.transactions);let paymentPreferences=read(KEYS.preferences,{promo:true,corporate:true,personal:true,card:true,digitalWallet:"Apple Pay"});
if(!cards.length){const saved=read(KEYS.payment,null);cards=saved?[{id:`card-${saved.last4||"4242"}`,brand:"VISA",last4:saved.last4||"4242",expiry:saved.expiry||"12/30",holder:saved.holder||"VoltDrive Driver",isDefault:true}]:defaults.cards;write(KEYS.cards,cards)}
write(KEYS.wallet,wallet);write(KEYS.transactions,transactions);
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
function profile(){const user=read(KEYS.profile,null)||getSession()||{};const name=user.name||user.fullName||"VoltDrive Driver";$("#sidebar-name").textContent=name;$("#sidebar-email").textContent=user.email||"driver@voltdrive.am";$("#billing-name").textContent=name;$("#billing-email").textContent=user.email||"driver@voltdrive.am";$("#avatar").textContent=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"VD"}
function activeVehicle(){const list=read(KEYS.vehicles,[]);const legacy=read(KEYS.vehicle,null);const item=list.find(v=>v.isActive)||list[0]||legacy;$("#vehicle-selector").textContent=item?`${item.manufacturer||"Tesla"} ${item.model||"Model Y"}`:"Add vehicle"}
function renderBalances(){$("#personal-balance").textContent=money(wallet.personal);$("#corporate-balance").textContent=money(wallet.corporate);$("#promo-balance").textContent=money(wallet.promo);$("#header-wallet-balance").textContent=money(wallet.personal)}
function renderCards(){const list=$("#payment-method-list");list.innerHTML=cards.map(card=>`<article class="payment-card ${card.isDefault?"is-default":""}"><span class="payment-card__brand">${card.brand}</span><div class="payment-card__copy"><strong>•••• •••• •••• ${card.last4}${card.isDefault?'<span class="default-badge">DEFAULT</span>':""}</strong><span>${card.holder} · Expires ${card.expiry}</span></div><div class="payment-card__actions">${!card.isDefault?`<button type="button" data-default-card="${card.id}" title="Make default">✓</button>`:""}<button type="button" data-remove-card="${card.id}" title="Remove">×</button></div></article>`).join("");const select=$("#funds-card");select.innerHTML=cards.map(card=>`<option value="${card.id}">${card.brand} •••• ${card.last4}${card.isDefault?" — Default":""}</option>`).join("")}
function renderTransactions(){const type=$("#transaction-filter").value;const filtered=transactions.filter(item=>type==="all"||item.type===type);$("#transaction-list").innerHTML=filtered.map(item=>`<article class="transaction-row"><span class="transaction-icon transaction-icon--${item.type}">${item.type==="topup"?"+":item.type==="refund"?"↩":"ϟ"}</span><div class="transaction-copy"><strong>${item.title}</strong><span>${item.meta}</span></div><div class="transaction-amount ${item.amount>0?"is-positive":""}"><strong>${item.amount>0?"+":"−"}${money(Math.abs(item.amount))}</strong><span>${item.id}</span></div></article>`).join("")||'<div class="topup-note">No matching financial activity.</div>'}
function renderTopup(){const enabled=$("#auto-topup-toggle");enabled.checked=wallet.autoTopup;$("#topup-threshold").value=String(wallet.threshold);$("#topup-amount").value=String(wallet.topupAmount);$("#topup-note").textContent=wallet.autoTopup?`Your default card will be charged ${money(wallet.topupAmount)} when your balance falls below ${money(wallet.threshold)}.`:"Automatic top-up is disabled."}
function renderPaymentSources(){const sources=[{id:"promo",title:"Promo credits",meta:"Used first when available",amount:wallet.promo},{id:"corporate",title:"Corporate balance",meta:"Company charging allowance",amount:wallet.corporate},{id:"personal",title:"Personal wallet",meta:"Your prepaid VoltDrive balance",amount:wallet.personal},{id:"card",title:"Default bank card",meta:`${cards.find(card=>card.isDefault)?.brand||"VISA"} •••• ${cards.find(card=>card.isDefault)?.last4||"4242"}`,amount:null}];$("#payment-source-list").innerHTML=sources.map(source=>`<label class="payment-source-option ${paymentPreferences[source.id]?"is-enabled":""}"><input type="checkbox" data-payment-source="${source.id}" ${paymentPreferences[source.id]?"checked":""}><span class="payment-source-option__copy"><strong>${source.title}</strong><span>${source.meta}</span></span><span class="payment-source-option__amount">${source.amount===null?"Fallback":money(source.amount)}</span></label>`).join("");const enabled=sources.filter(source=>paymentPreferences[source.id]).map(source=>source.title.replace(" credits","").replace(" balance","").replace(" wallet","").replace(" bank card"," card"));$("#payment-source-order").textContent=enabled.length?enabled.join(" → "):"No payment source selected"}
let toastTimer;function toast(message){const node=$("#wallet-toast");node.textContent=message;node.classList.add("is-visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("is-visible"),2600)}
function openModal(id){const modal=document.getElementById(id);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}function closeModal(id){const modal=document.getElementById(id);modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
$("#add-funds-button").addEventListener("click",()=>openModal("funds-modal"));$("#balance-add-funds").addEventListener("click",()=>openModal("funds-modal"));$("#add-card-button").addEventListener("click",()=>openModal("card-modal"));$$('[data-close-modal]').forEach(button=>button.addEventListener("click",()=>closeModal(button.dataset.closeModal)));
$$('[data-amount]').forEach(button=>button.addEventListener("click",()=>{$$('[data-amount]').forEach(x=>x.classList.remove("is-selected"));button.classList.add("is-selected");$("#funds-amount").value=button.dataset.amount}));
$("#funds-form").addEventListener("submit",event=>{event.preventDefault();const amount=Number($("#funds-amount").value);if(!Number.isFinite(amount)||amount<1000){toast("Enter an amount of at least 1,000 AMD.");return}wallet.personal+=amount;transactions.unshift({id:`TX-${Date.now().toString().slice(-6)}`,type:"topup",title:"Wallet top-up",meta:`${cards.find(c=>c.id===$("#funds-card").value)?.brand||"Card"} •••• ${cards.find(c=>c.id===$("#funds-card").value)?.last4||"4242"} · Just now`,amount});write(KEYS.wallet,wallet);write(KEYS.transactions,transactions);addNotification({type:"payment",title:"Wallet top-up successful",message:`${money(amount)} was added to your personal wallet.`,action:{label:"Open wallet",href:"./wallet.html"}});syncCommonUi();renderBalances();renderTransactions();closeModal("funds-modal");toast(`${money(amount)} added to your wallet.`)});
$("#card-form").addEventListener("submit",event=>{event.preventDefault();const data=new FormData(event.currentTarget);const digits=String(data.get("number")).replace(/\D/g,"");if(digits.length<12){toast("Enter a valid card number.");return}cards.push({id:`card-${Date.now()}`,brand:digits.startsWith("5")?"MC":"VISA",last4:digits.slice(-4),expiry:String(data.get("expiry")),holder:String(data.get("holder")),isDefault:cards.length===0});write(KEYS.cards,cards);renderCards();event.currentTarget.reset();closeModal("card-modal");toast("Payment card added.")});
$("#payment-method-list").addEventListener("click",event=>{const defaultButton=event.target.closest("[data-default-card]");const removeButton=event.target.closest("[data-remove-card]");if(defaultButton){cards=cards.map(card=>({...card,isDefault:card.id===defaultButton.dataset.defaultCard}));write(KEYS.cards,cards);renderCards();toast("Default card updated.")}if(removeButton){if(cards.length===1){toast("At least one payment method is required.");return}const removing=cards.find(card=>card.id===removeButton.dataset.removeCard);cards=cards.filter(card=>card.id!==removeButton.dataset.removeCard);if(removing?.isDefault&&cards[0])cards[0].isDefault=true;write(KEYS.cards,cards);renderCards();toast("Payment card removed.")}});
$("#payment-source-list").addEventListener("change",event=>{const input=event.target.closest("[data-payment-source]");if(!input)return;paymentPreferences[input.dataset.paymentSource]=input.checked;write(KEYS.preferences,paymentPreferences);renderPaymentSources();toast("Payment order updated.")});
$$('[data-digital-wallet]').forEach(button=>button.addEventListener("click",()=>{paymentPreferences.digitalWallet=button.dataset.digitalWallet;write(KEYS.preferences,paymentPreferences);toast(`${button.dataset.digitalWallet} selected for this prototype.`)}));
$("#preview-failed-payment").addEventListener("click",()=>openModal("payment-recovery-modal"));
$("#retry-payment").addEventListener("click",()=>{const amount=3480,source=$("#recovery-source").value;let paid=false;if(source==="promo"&&wallet.promo>=amount){wallet.promo-=amount;paid=true}else if(source==="corporate"&&wallet.corporate>=amount){wallet.corporate-=amount;paid=true}else if(source==="personal"&&wallet.personal>=amount){wallet.personal-=amount;paid=true}else if(source==="card"){paid=true}if(!paid){toast("The selected balance is not sufficient.");return}transactions.unshift({id:`TX-${Date.now().toString().slice(-6)}`,type:"payment",title:"Recovered charging payment",meta:`Session CS-0001542 · ${source} · Just now`,amount:-amount,status:"paid"});write(KEYS.wallet,wallet);write(KEYS.transactions,transactions);addNotification({type:"payment",title:"Payment recovered",message:`The pending ${money(amount)} payment was completed successfully.`,action:{label:"Open wallet",href:"./wallet.html"}});renderBalances();renderTransactions();renderPaymentSources();syncCommonUi();closeModal("payment-recovery-modal");toast("Payment completed successfully.")});
$("#preview-partial-refund").addEventListener("click",()=>{const amount=1200;wallet.personal+=amount;transactions.unshift({id:`TX-${Date.now().toString().slice(-6)}`,type:"refund",title:"Partial charging refund",meta:"Session CS-0001542 · Just now",amount,status:"partially-refunded"});write(KEYS.wallet,wallet);write(KEYS.transactions,transactions);addNotification({type:"payment",title:"Partial refund issued",message:`${money(amount)} was returned to your personal wallet.`,action:{label:"View payment",href:"./wallet.html"}});renderBalances();renderTransactions();renderPaymentSources();syncCommonUi();toast("Partial refund added to your wallet.")});
$("#open-payment-dispute").addEventListener("click",()=>{const disputes=read(KEYS.disputes,[]);const dispute={id:`DSP-${Date.now().toString().slice(-6)}`,sessionId:"CS-0001542",amount:3480,status:"open",createdAt:new Date().toISOString()};write(KEYS.disputes,[dispute,...disputes]);addNotification({type:"payment",title:"Payment dispute opened",message:`Dispute ${dispute.id} is now under review.`,action:{label:"Contact support",href:"./support.html"}});closeModal("payment-recovery-modal");toast(`Dispute ${dispute.id} opened.`)});
function updateTopup(){wallet.autoTopup=$("#auto-topup-toggle").checked;wallet.threshold=Number($("#topup-threshold").value);wallet.topupAmount=Number($("#topup-amount").value);write(KEYS.wallet,wallet);renderTopup()}$("#auto-topup-toggle").addEventListener("change",updateTopup);$("#topup-threshold").addEventListener("change",updateTopup);$("#topup-amount").addEventListener("change",updateTopup);$("#transaction-filter").addEventListener("change",renderTransactions);
$$('[data-demo-message]').forEach(button=>button.addEventListener("click",()=>toast(button.dataset.demoMessage)));$$('[data-coming-soon]').forEach(button=>button.addEventListener("click",event=>{event.preventDefault();toast(`${button.dataset.comingSoon} will be added in the next stages.`)}));
$("#logout-button").addEventListener("click",()=>{clearSession();location.href="./login.html"});
$("#menu-toggle").addEventListener("click",()=>document.body.classList.toggle("sidebar-open"));$("#mobile-overlay").addEventListener("click",()=>document.body.classList.remove("sidebar-open"));
profile();activeVehicle();syncCommonUi();renderBalances();renderCards();renderTransactions();renderTopup();renderPaymentSources();
